### ISSUE TITLE
Object mismatch with pymongo FixedOffset

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#117]
I've discovered that the round-trip serialization/deserialization of a simple FixedOffset object produces a corrupted object. The output of [this test script](https://gist.github.com/jaraco/d979a558bc0bf2194c23/079efd37a641159c0c14a1ab93f7efce30bf3eda) produces:

```
============================= test session starts =============================
platform win32 -- Python 3.4.2 -- py-1.4.26 -- pytest-2.6.4
collected 1 items

test_fo.py F

================================== FAILURES ===================================
________________________ test_FixedOffsetSerializable _________________________

    def test_FixedOffsetSerializable():
    	import jsonpickle
    	import bson.tz_util
    	fo = bson.tz_util.FixedOffset(-60*5, 'EST')
    	serialized = jsonpickle.dumps(fo)
    	pprint.pprint(json.loads(serialized))
    	restored = jsonpickle.loads(serialized)
    	print(restored._FixedOffset__offset)
>   	assert restored == fo
E    assert <bson.tz_util.FixedOffset object at 0x0000000005F494A8> == <bson.tz_util.FixedOffset object at 0x0000000005EEFA90>

test_fo.py:16: AssertionError
---------------------------- Captured stdout call -----------------------------
{'_FixedOffset__name': 'EST',
 '_FixedOffset__offset': {'py/id': 1},
 'py/initargs': {'py/tuple': [{'__reduce__': [{'py/type': 'datetime.timedelta'},
                                              {'py/tuple': [-1, 68400, 0]}],
                               'py/object': 'datetime.timedelta'},
                              'EST']},
 'py/object': 'bson.tz_util.FixedOffset'}
<bson.tz_util.FixedOffset object at 0x0000000005F494A8>
========================== 1 failed in 0.52 seconds ===========================
```

As you can see, the object produced isn't equal to the one serialized. Furthermore, it appears as if the `.__offset` property of the object has been set to itself instead of the timedelta object.

**Comment by marcintustin** [comment]
Does it roundtrip correctly with pickle? I wonder if there are two problems here - one with the pickling machinery they provide, and one with ours.

**Comment by jaraco** [comment]
The roundtrip does work correctly with stdlib pickle. Here's [rev 3 of the test script](https://gist.github.com/jaraco/d979a558bc0bf2194c23/4391e5ea2ae8ac8ace31904e4799b3dc49fada10) where the first test still fails, but the other two succeed.

**Comment by jaraco** [comment]
I've stepped through the flattening code, and I believe the serialized version is correct (the `{'py/id': 1}` is the correct reference as the `FixedOffset` object is the first object serialized (index 0) and the `timedelta` is the second object serialized (index 1).

**Comment by jaraco** [comment]
The issue appears to be in `Unpickler._swapref`. Here's my pdb session during the unpickling during the test:

```
> c:\users\jaraco\p\jsonpickle\jsonpickle\unpickler.py(288)_restore_object_instance()
-> self._swapref(proxy, instance)
﻿(Pdb) self._objs
[<jsonpickle.unpickler._Proxy object at 0x000000000686AC88>, datetime.timedelta(-1, 68400)]
﻿(Pdb) n
> c:\users\jaraco\p\jsonpickle\jsonpickle\unpickler.py(290)_restore_object_instance()
-> if isinstance(instance, tuple):
﻿(Pdb) self._objs
[<jsonpickle.unpickler._Proxy object at 0x000000000686AC88>, <bson.tz_util.FixedOffset object at 0x0000000006841320>]
```

Instead of replacing the Proxy reference, `_swapref` appears to be replacing the timedelta instance with the new FixedOffset instance.

**Comment by jaraco** [comment]
I've figured out the issue and I'm writing a test now to capture the failure in jsonpickle.
