### ISSUE TITLE
pickling a dictionary converts keys to strings

### ISSUE THREAD

**Issue by jonredgrave** [jsonpickle/jsonpickle#127]
>>> import jsonpickle; jsonpickle.loads(jsonpickle.dumps({1:1}))
{u'1': 1}

**Comment by johnpaulett** [comment]
Unfortunately, json's spec defines object keys as strings:
via http://json.org/:
![json-object](https://cloud.githubusercontent.com/assets/30702/7413649/80925588-ef1b-11e4-9495-6ba9576f2a32.gif)

Perhaps there is a more complex way to solve, but you would also run into this issue using the default json package:
```
>>> import json
>>> json.dumps({1:1})
 '{"1": 1}'
```

**Comment by davvid** [comment]
In addition to John's notes, we do support this if you pass
keys=True to jsonpickle when encoding and decoding:

    >>> import jsonpickle
    >>> jsonpickle.decode(jsonpickle.encode({1: 1}, keys=True), keys=True)
    {1: 1}
