### ISSUE TITLE
Registered Handlers fail to fire

### ISSUE THREAD

**Issue by christopherreay** [jsonpickle/jsonpickle#128]
So ive looked through jsonpickle.handlers._registry and ._base_registry

My handler is registered. I have checked the type(object) and it is the same as registered in the registry.
Ive registered the base handler as a base handler

The code in customHandlers is never called whilst jsonpickle goes into an infinite loop (which it wouldnt was it using the custom handlers to pickle), also I have debug statements in the code which are never called. 

I am directly calling jsonpickle.encode(categories) where categories is of the type registered in the registry.

Whats going on here? Ive looked at the source and there is a clear call into the handlers object to search for the correct handler, so I dont know what is going 

This is frustrating because if I override _ _getstate_ _ it all works perfectly, but the zodb persistent objects all break. So i have just created a handler for my root Class and changed the method to something else.

source for handler is here: http://pastebin.com/yniug8zE

**Comment by mtustin-handy** [comment]
It would help to have some code which demonstrates the problem.

**Comment by marcintustin** [comment]
It would help to have some code which demonstrates the issue.

**Comment by christopherreay** [comment]
I was editting the pastebin as you spoke! Thanks :)

**Comment by christopherreay** [comment]
For what I am doing, jsonpickle is not relevant, I have just extended json.JSONEncoder.

If i need to use jsonpicklejs, Ill get back to you.
If you manage to find out what is wrong, Id love to hear about it

**Comment by davvid** [comment]
Life is too short to debug your scripts.  Sorry!
