### ISSUE TITLE
Wrong type after decode

### ISSUE THREAD

**Issue by JoaoFelipe** [jsonpickle/jsonpickle#138]
When it decodes a defaultdict, it looses the type information from keys:

``` python
In   [1]: import jsonpickle

In   [2]: from collections import defaultdict

In   [3]: thing = defaultdict(list)

In   [4]: thing[1].append(2)

In   [5]: thing
Out  [5]: defaultdict(<class 'list'>, {1: [2]})

In   [6]: thing[1]
Out  [6]: [2]

In   [7]: frozen = jsonpickle.encode(thing)

In   [8]: frozen
Out  [8]: '{"default_factory": {"py/type": "__builtin__.list"}, "py/object": "collections.defaultdict", "1": [2]}'

In   [9]: thawed = jsonpickle.decode(frozen)

In  [10]: thawed
Out [10]: defaultdict(<class 'list'>, {'1': [2]})

In  [11]: thawed[1]
Out [11]: []

In  [12]: thawed['1']
Out [12]: [2]
```

Note that the int was converted into a string

**Comment by Shados** [comment]
More generally: integer keys in dictionaries of any type are converted to strings by the encode/decode process.

**Comment by davvid** [comment]
Please RTFM
https://jsonpickle.readthedocs.io/en/latest/api.html#jsonpickle-high-level-api

Pay attention to the "keys" flag.

**Comment by JoaoFelipe** [comment]
Thanks for the reply! Unfortunately, it has been 5 years and I don't use this project anymore. 

Anyway, your answer with "RTFM" was kind of rude for an old issue like that. I suppose you updated the docs many times since I submitted the issue (the version that I used to use does not even appear in the readthedocs page). 
But I understand you. Based on the description of "keys" (`This is typically what you want if you need to support Integer or objects as dictionary keys.`), you probably receive many similar issues. If you keep receiving issues like this, I suggest you to give more emphasis to this parameter. Maybe use bold or present it in the examples of usage.

**Comment by davvid** [comment]
Thanks for the sug.  The docs now point out these details on both the front page and at the very top of the API docs in hopes of eliminating bug reports of this nature in the future.  The docs were improved thanks to you.

Please understand that RTFM before filing a bug report is common courtesy.  Some even consider it rude not to do so. 😸 j/k

That comment was not really intended for you.  It's for everyone else who stumbles upon this bug report in the future and needs to be pointed in the right direction. Closing the bug without leaving a succinct comment explaining what to do would have been naughty.

Thanks again.
