### ISSUE TITLE
problem convert list object to JSON string

### ISSUE THREAD

**Issue by RaminFP** [jsonpickle/jsonpickle#141]
output a record list sqlalchemy : 

{"py/object": "Models.UserModel.", "_sa_instance_state": {"py/object": "sqlalchemy.orm.state.InstanceState", "py/state": {"instance": {"py/id": 0}, "committed_state": {}, "class_": {"py/type": "Models.UserModel."}, "manager": {"py/object": "sqlalchemy.orm.instrumentation._SerializeManager", "class_": {"py/type": "Models.UserModel.Student"}}, "key": {"py/tuple": [{"py/type": "Models.UserModel.Student"}, {"py/tuple": [1]}]}, "expired_attributes": {"py/set": []}}}, "name": "ramin", "fullname": "eee", "password": "1234345", "id": 1}

just i need : 
{"name": "ramin", "fullname": "eee", "password": "1234345", "id": 1} how to use?

**Comment by rozymahsun** [comment]
same here

**Comment by Theelx** [comment]
You'd be looking for json.dumps then, with a custom converter or something. Jsonpickle won't provide such bare-bones output because that output can't be used to fully deserialize the class.
