### ISSUE TITLE
Add ability to decode an object from a dict/json string based on provided class

### ISSUE THREAD

**Issue by nyxcalamity** [jsonpickle/jsonpickle#148]
Would be nice to have some functionality that allows object recreation based on provided class. For example:

```
class Thing(object):
    def __init__(self, name):
        self.name = name

obj = Thing('Awesome')
import jsonpickle
oneway = jsonpickle.encode(obj, unpicklable=False)
result = jsonpickle.decode(oneway, Thing) # or Thing.__class__
assert obj.name == result.name
```

**Comment by y0rd4nis** [comment]
Right now I'm decoding the json string into dict, updating the dict with the corresponding object class, encoding back the updated dict to json string and then calling jsonpickle.decode(...).

>  json_dict = json.loads(json_str)
>  json_dict.update({"py/object": "module.Class"})
> obj = jsonpickle.loads(json.dumps(json_dict))

It works, but it will be nice if the desired class can be provided to jsonpickle.decode(...), like @nyxcalamity says, or specifying the python path to the object class.

**Comment by ejwessel** [comment]
I have a similar problem.

Using the above solution provided by @y0rd4nis I've made the following. Though I don't like it and I'm still open for alternative solutions that are better.
```
from jsonpickle import encode, decode
import json

def to_json(obj):
    return encode(obj)

def from_json(desired_obj, json_str):
    '''
    This essentially seals the py/object info from a passed class
    The big problem with this method is that if the desired_obj has parameters, you'll need pass blanks
    :param desired_obj: instantiated object that we want to
    :param json_str: 
    :return: 
    '''
    object_type = desired_obj.__module__ + "." + desired_obj.__class__.__name__
    json_dict = json.loads(json_str)
    json_dict.update({"py/object":object_type})
    return decode(json.dumps(json_dict))
```

**Comment by ejwessel** [comment]
Here's a better method where you don't have to create a blank object and can only provide the type

```
def from_json2(class_type, json_str):
    type_dict_str = to_json(class_type)
    json_type_dict = json.loads(type_dict_str)
    json_dict = json.loads(json_str)
    json_dict.update({"py/object": json_type_dict["py/type"]})
    return decode(json.dumps(json_dict))
```

```
newObj2 = from_json2(ClassName, json_str)
print isinstance(newObj2, ClassName) -----> True
```

**Comment by ejwessel** [comment]
Regardless of the solutions above there might be a correct way instead of the work arounds proposed, but I was came up short on solutions. 

If anybody comes across this in the future and has the right one, then please comment.

**Comment by davvid** [comment]
I forgot to update this issue when #161 was addressed since it's relevant here.

You should be able to do `decode(jsonstr, classes=Thing)` or `classes=(Thing, OtherThing, ...))` and it should recognize your local classes when encoded using jsonpickle.  That should solve any problems related to local classes that can't be found by jsonpickle via module imports, which  may have been related here.

if you want to interact with a dict directly, then you should probably use the `jsonpickle.unpickler.Unpickler` class directly since its `restore()` method expects a dict instead of raw json.  Likewise, `jsonpickle.pickler.Pickler.flatten()` to product dicts from objects.

If you want to "decorate" a dict with the metadata to make it decode as if it's a class then you should be able to safely use this snippet.

```
import jsonpickle
import jsonpickle.tags as tags
import jsonpickle.unpickler as unpickler
import jsonpickle.util as util

class Thing(object):
    pass

dct = {}
dct[tags.OBJECT] = util.importable_name(Thing)
dct['name'] = 'awesome'

obj = unpickler.Unpickler().restore(dct, classes=Thing)
assert isinstance(obj, Thing)
assert obj.name == 'awesome'
```

As usual, if `Thing` is importable (and not a local class in an inaccessible scope as detailed in #161) then you don't need `classes=...`.

Hope that helps.

**Comment by knightliao** [comment]
your method is not working when the new 'classes''s module path is changed compared with the previous. 

You can use the following method if you want to specify your own class. It only requires that name of the two classes must be same. 

execute jsonpickle_class_patch() before your program. 

```
def jsonpickle_class_patch():
    old_processor = jsonpickle.unpickler.loadclass

    def loadclass(module_and_name, classes=None):
        ret = old_processor(module_and_name, classes)
        if ret is None:
            target_module, target_name = module_and_name.rsplit('.', 1)
            for class_path in classes:
                current_module, current_name = class_path.rsplit('.', 1)
                if current_name == target_name:
                    return classes[class_path]
        return ret

    jsonpickle.unpickler.loadclass = loadclass

```

**Comment by jannismain** [comment]
Thanks @knightliao! This was exactly the snippet I was looking for to deserialize objects without access to the original class.

**Comment by jannismain** [comment]
In general, I like the idea of optionally deserializing objects based on the class name alone, not the fully qualified name.

Although, for my personal use case the deserialized class didn't necessarily have the same name as the original one, so It would not solve my use case per se. A kind of user-configurable mapping would do that, but It might not be worth the complexity 🤷🏻 

Example of my use case:

```json
{
    "py/object": "Parent.Middle.BaseClass",
    ...
}
```

is deserialized into `ParentShim` like this:

```py
def loadclass(module_and_name, classes=None):
        # prioritize shim for any Parent subclass
        if module_and_name.startswith("Parent.Middle"):
            logging.debug("Using shim for '%s'", module_and_name)
            return ParentShim
```

A user-configurable mapping could look like this:

```py
import ParentShim

custom_json_loader_mapping = [
    {
        "original": "Parent\.Middle\..*"
        "restore": ParentShim
    },
    ...
]
```

Or am I making this more complicated than it needs to be?

**Comment by Theelx** [comment]
Why can't you just pass a dict to classes like so:
```py
import jsonpickle

# pretend this first class is defined in an unreachable file
class Thing:
    __slots__ = ("x",)
    def __init__(self):
        self.x = 1

class Thing2:
    __slots__ = ("x", "y")
    def __init__(self):
        self.y = 1

strthing = jsonpickle.encode(unreachable_file.Thing())
result = jsonpickle.decode(strthing, classes={"Thing": Thing2})
```
Shouldn't result now give you an instance of Thing2, like you wanted?

**Comment by Theelx** [comment]
Whoopsie, it seems one can't pass a dict to classes. That's dumb, I'm going to make it allow that.

**Comment by Theelx** [comment]
This case should still work for an n:1 mapping between original object and shim. Just pass the same value for multiple different keys. However, you're right in that it won't work if not all the names are known by the receiving code. I think that use case is exotic enough that overloading `loadclass` is a reasonable method to achieve the results you want, but sadly I don't think it's common enough to warrant inclusion into the actual library. If other people come across this issue later and thinks it's worth inclusion then I might add a dedicated option for your behavior though.
