### ISSUE TITLE
Local module queue being picked up by jsonpickle rather than jsonpickle's queue module

### ISSUE THREAD

**Issue by davidhariri** [jsonpickle/jsonpickle#160]
I can't use jsonpickle because we have a module in the root of our project called queue:
```
  File "/Users/davidhariri/Development/Ada/api/env/lib/python2.7/site-packages/jsonpickle/handlers.py", line 267, in <module>
    QueueHandler.handles(queue.Queue)
AttributeError: 'module' object has no attribute 'Queue'
```
Can we consider renaming jsonpickle's queue module to "jsp_queue" or some other more localized name?

**Comment by davvid** [comment]
No, you're clashing with Python's built-in `queue` module.  You should rename your module.

pylint or another checker should be able to catch that.  You're masking the standard library, jsonpickle is just a canary in the coal mine.
