### ISSUE TITLE
jsonpickle on python 3.5 decode to dict instead of object

### ISSUE THREAD

**Issue by ifanchu** [jsonpickle/jsonpickle#161]
I am using jsonpickle to encode/decode complex classes in my projects. 
jsonpickle works perfectly in python 2.7, but now I need to make my code compatible for both python 2.7 and python 3.5.2.

I have a simple unit test for this and it works fine in 2.7 but it decodes to a dict instead of object in 3.5.2, I must be missing something, please help. 

    class TestClass(object):
        def __init__(self):
            self.attr2 = [1, 2, 3, 4]

    class TestJsonpickle(unittest.TestCase):
        def test_jsonpickle(self):
            import jsonpickle

            obj = TestClass()
            encoded = jsonpickle.encode(obj)
            robj = jsonpickle.decode(encoded)
            self.assertEqual(obj.__class__.__name__, robj.__class__.__name__)

The encoded string is 

    '{"attr2": [1, 2, 3, 4], "py/object": "tests.unittests.test_tasking.TestClass"}'

jsonpickle version is 0.9.4

**Comment by ifanchu** [comment]
It works if I put the TestClass to another module, so I am closing this issue.

**Comment by danac** [comment]
I'm having the same problem with Python 3.5 and 3.6 (on 64 bit Windows 7):
`
>>> import jsonpickle
>>> class Thing(object):
    def __init__(self, name):
        self.name = name

obj = Thing('Awesome')
>>> obj
<Thing object at 0x00000000035D5F98>
>>> jsonpickle.decode(jsonpickle.encode(obj))
{'py/object': '__builtin__.Thing', 'name': 'Awesome'}
`

**Comment by davvid** [comment]
I have a solution for this coming shortly. You'll be able to do `jsonpickle.decode(json_string, classes=Thing)` to make the local `Thing` class visible to jsonpickle.
