### ISSUE TITLE
TravisCI inactive?

### ISSUE THREAD

**Issue by marscher** [jsonpickle/jsonpickle#166]
It would be preferable to run the tests automatically on changes/PRs.

**Comment by davvid** [comment]
@johnpaulett maybe you can enable the settings in github?  We currently have to enable it in our own forks, but it would be much appreciated having it for the main one too so that it tests PRs automatically.

**Comment by johnpaulett** [comment]
I believe I've enabled the settings now, just waiting on next commit (I don't see a way to trigger a first job on travis):
https://travis-ci.org/jsonpickle/jsonpickle

**Comment by marscher** [comment]
thanks @johnpaulett. It works now!
