### ISSUE TITLE
jsonpickle should more clearly warn about security hazard

### ISSUE THREAD

**Issue by ssbr** [jsonpickle/jsonpickle#178]
For example, there exists a "safe" flag that tries to be safe. But does it protect against attacks? Not quite:

    >>> jsonpickle.unpickler.decode("""
    ...     {"py/object": "__builtin__.eval",
    ...     "py/initargs": {"py/tuple": ["__import__('os').system('sh')"]}}
    ... """, safe=True)
    sh-4.3$

or:

    >>> jsonpickle.unpickler.decode('{"py/reduce": [{"py/function": "os.system"},["sh"],0,0,0]}', safe=True)
    sh-4.3$ 

Probably this should be deprecated.

Also, currently the docs at https://jsonpickle.github.io/ only say (and only halfway down the page):

> Warning: Loading a JSON string from an untrusted source represents a potential security vulnerability. jsonpickle makes no attempt to sanitize the input.

This is too weak. Loading a jsonpickle from an untrusted source is _always_ a security vulnerability.

Compare with the pickle docs, which are much clearer, and put this right at the very top of the page rather than below the fold:

> Warning: The pickle module is not secure against erroneous or maliciously constructed data. Never unpickle data received from an untrusted or unauthenticated source.

**Comment by davvid** [comment]
Agreed.  Writing is not my forte, but your paragraphs is very nicely written.  Would you mind sending a PR against the docs, please?
