### ISSUE TITLE
[Wishlist] Add indent & sort_keys support for dumps() method

### ISSUE THREAD

**Issue by n3h3m** [jsonpickle/jsonpickle#183]
The original `json` module's dumps() contain these two parameters which can be used occasionally to prettify objects. However, the built-in `json` module has its own limitation. 

I would prefer to use `jsonpicke.dumps()` to achieve this if we support the parameters `sort_keys` and `indent` 

Medod signature of `json.dumps()`
```
def dumps(obj, *, skipkeys=False, ensure_ascii=True, check_circular=True,
        allow_nan=True, cls=None, indent=None, separators=None,
        default=None, sort_keys=False, **kw):
    """Serialize ``obj`` to a JSON formatted ``str``.

    
    If ``indent`` is a non-negative integer, then JSON array elements and
    object members will be pretty-printed with that indent level. An indent
    level of 0 will only insert newlines. ``None`` is the most compact
    representation.

    If *sort_keys* is true (default: ``False``), then the output of
    dictionaries will be sorted by key.

    """
```

**Comment by VSZM** [comment]
Workaround for pretty formatting with jsonpickle using the standard json backend:

`json.dumps(json.loads(jsonpickle.encode(your_object)), indent=4, sort_keys=True)`

**Comment by davvid** [comment]
`sort_keys` is problematic.  It can and will break things so that is totally off the table.

`indent` could be helpful, so I'm looking into adding that now.
