### ISSUE TITLE
Not possible to invoke serialization/deserialization handlers for nested objects?

### ISSUE THREAD

**Issue by rlubke** [jsonpickle/jsonpickle#186]
I have a simple object graph which I want to serialize across the wire to a java backend.

Consider the following:

```python
class Put(NamedCacheRequest):
    def __init__(self, cache_name: str=None, key: K=None, value: V=None) -> None:
        super().__init__(cache_name)
        self.key = key
        self.value = value

    def flatten(self, obj, data):
        super().flatten(obj, data)
        data["key"] = obj.key
        data["value"] = obj.value
        return data

    def restore(self, obj):
        pass
```

In the above example, value can be a simple or complex type.  With simple types, it works fine.
However, here's the wrench (perhaps perceived):

```python
class Person(object):
    def __init__(self, name: str, age: int, gender: str, friends: set):
        super().__init__()
        self.name = name
        self.age = age
        self.gender = gender
        self.friends = friends

    def __eq__(self, o: object) -> bool:
        if not isinstance(o, Person):
            return False

        return self.name == o.name and self.age == o.age and self.gender == o.gender and self.friends == o.friends

    def __ne__(self, o: object) -> bool:
        return not self.__eq__(o)
```

I have a handler registered for Person to deal with serialization of the set, however, the handler is never invoked.   Of course, if I pass a Person object directly to jsonpickle, then the handler is invoked as expected.

I can go into details on why I'm not letting jsonpickle encode the set, i.e., py/set in the stream, if desired.

**Comment by davvid** [comment]
Just curious, what was the solution?  If possible, I'd be happy to include a test case that mimics your use case.

**Comment by rlubke** [comment]
@davvid I think once you use a handler you're in complete control of what is serialized and what isn't.   The jsonpickle runtime won't inspect the result of data to see if further serialization is required.

So for now, I've written my own internal flatten method that can be called to invoke any handlers found for that type.

So using the example above, with nested Person types, I have:

```python
def flatten(self, obj, data):
        data["name"] = obj.name
        data["age"] = obj.age
        data["gender"] = obj.gender
        if obj.friends is not None:
            data["friends"] = [self.flatten_internal(i) for i in obj.friends]
        return data
```

**Comment by rlubke** [comment]
@davvid Though that leaves the question on how to deserialize nested objects.

Consider the following:

```python
friends = [Person("Aragorn", 90, "male"), Person("Gimli", 150, "male?")]
bilbo = Person("Bilbo", 111, "male", friends)
frodo = Person("Frodo", 33, "male", friends)

result = encode(bilbo)
b = decode(result)
self.assertEqual(bilbo, b)
```

I could go the hack route, and convert the dict back to string and call decode,  but there is probably a better way....

**Comment by rlubke** [comment]
#davvid Disregard that last question.  Think I have that resolved now too.
