### ISSUE TITLE
Can coroutines be serialized?

### ISSUE THREAD

**Issue by radek-sprta** [jsonpickle/jsonpickle#191]
I ran upon a problem, when trying to serialize coroutines:

(Pdb) result
<coroutine object results at 0x7fa0c81b4830>
(Pdb) jsonpickle.decode(jsonpickle.encode(result))
{'py/object': '__builtin__.coroutine'}
(Pdb) jsonpickle.decode(jsonpickle.encode(result)) == result
False

Is that the expected behavior? And if so, any hints on how to extend jsonpickle to properly serialize coroutines?

**Comment by dargueta** [comment]
According to the Python documentation for [`pickle`](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled), no.

**Comment by radek-sprta** [comment]
That makes sense. Thanks!
