### ISSUE TITLE
Consider folding in features from jsonstruct project

### ISSUE THREAD

**Issue by rlubke** [jsonpickle/jsonpickle#194]
https://github.com/initialxy/jsonstruct

This project is a fork of an older version of JSON pickle.  Why is this of interest?

I'm currently working a polyglot key/value store that uses JSON to push/pull data between different clients.

For example, we're currently able to share data between Java, Go, Swift, and JS clients.  Python is currently working using jsonpickle.  However, the Python client is not able to handle JSON that was generated by other clients as the type info isn't nested in the JSON stream.

Enter jsonstruct.  Instead of embedding the type info, you pass the class or an instance to the decode operation and it populates the instance based on the parsed JSON.  This is very similar to how Go and Swift work.

Unfortunately, jsonstruct appears to be abandoned.  The last update was five years ago and there appears, based on the issue tracker, to be a compatibility issue with Python 3. 

It seems the ideas from jsonstruct could be a useful addition to jsonpickle to allow it to interoperate better with non-python clients.

Thoughts?

**Comment by marcintustin** [comment]
Feel free to make a PR? Quite possibly, you could simply add some functionality to alias types.

**Comment by rlubke** [comment]
Could you expand on the alias types comment?
