### ISSUE TITLE
Should primitives be encoded with repr after reaching max_depth

### ISSUE THREAD

**Issue by Mark-Hetherington** [jsonpickle/jsonpickle#198]
When max_depth is reached, or when make_refs is unset and the object has already been seen, the data is returned with repr(), in order to stop recursing or break a cycle. For unicode objects this results in a "u'text data'" in the JSON output. Given that primitives have no possibility of continuing a recursion or cyclical reference, would it not be better to return the object?

e.g. instead of 
`if max_reached or (not self.make_refs and id(obj) in self._objs):`
Perhaps:
`if (max_reached or (not self.make_refs and id(obj) in self._objs)) and not util.is_primitive(obj):`
or 
`if (max_reached and not util.is_primitive(obj)) or (not self.make_refs and id(obj) in self._objs):`
Is there any reason within _flatten_obj() to not check utils.is_primitive and simply return the object without calling _get_flattener()?

**Comment by davvid** [comment]
That seems very sensible.  There's probably not a strong reason, and perhaps an oversight.

**Comment by Mark-Hetherington** [comment]
nk, I will test on it a bit. I am Not sure what the best behaviour is when make_refs is true - but I don't think primitives are ever id() identical?
