### ISSUE TITLE
unpicklable=False with nested custom enums

### ISSUE THREAD

**Issue by opahopa** [jsonpickle/jsonpickle#208]
flag `unpicklable=False` is not working on my class with nested enums.

from enum import Enum

```
class MessageTypes(Enum):
    STATUS = 'STATUS',
    CONTROL = 'CONTROL'


class MessageStatus(Enum):
    OK = 'OK',
    ERROR = 'ERROR'


class MessageCommands(Enum):
    STATUS_ALL = 'STATUS_ALL'


class Message(object):

    def __init__(self, type, command, status=None, body=None):
        self.type = MessageTypes(type)
        if command:
            self.command = MessageCommands(command)
        if status:
            self.status = MessageStatus(status)
        if body:
            self.body = body

```

logger.info(jsonpickle.encode(msg, unpicklable=False)):

```
{
  "command": {
    "__objclass__": {
      "py\/type": "app.models.message.MessageCommands"
    },
    "_name_": "STATUS_ALL",
    "_value_": "STATUS_ALL"
  },
  "type": {
    "__objclass__": {
      "py\/type": "app.models.message.MessageTypes"
    },
    "_name_": "CONTROL",
    "_value_": "CONTROL"
  }
}
```

**Comment by davvid** [comment]
I don't quite understand what's "not working".  I added a test case to ensure we have coverage over this use case, but this issue doesn't actually assert anything about what does or does not work, so it's not very helpful.

What do you mean by "nested enum"?  The classes aren't nested -- they are simply member variables of the Message class.  That is well-supported -- please see the unit tests.

Please take a look at `tests/object_test.py` and run our unit tests using `make test`.   If something is not working, please report it in the form of a unit test that we can add to our test case.  This guarantees that your use case will be forever preserved.

That said, why are you using unpicklable=False?  Don't specify that flag and everything will work as expected.  FYI we don't support "unpickling" data generated by `unpicklable=False` -- that flag is a last-resort for use cases where we don't need to round-trip.  For example, one-directional data flows where something else (e.g. javascript) is consuming the json data and isn't trying to reconstruct the original python objects.
