### ISSUE TITLE
numpy ndarray encoding is broken

### ISSUE THREAD

**Issue by rfdougherty** [jsonpickle/jsonpickle#214]
```python
import numpy as np
import jsonpickle
import jsonpickle.ext.numpy as jsonpickle_numpy
jsonpickle_numpy.register_handlers()
jsonpickle.encode(np.random.random(100))
```

The problem seems to be a regression introduced in util.py b64encode by commit 3f87b87a87fc4c5bfe2ce5d7d59a40ab9ddc35cd (remove the not in line 515)

**Comment by philno** [comment]
I ran into the same problem when I tried to save a dictionary with a numeric field that came from numpy (np.random.choice from an integer array in my case).
Did you try the numpy handler as described in the readme? It seems to work for me.

```
import jsonpickle.ext.numpy as jsonpickle_numpy
jsonpickle_numpy.register_handlers()
```
