### ISSUE TITLE
Release 1.0 to PyPI?

### ISSUE THREAD

**Issue by hugovk** [jsonpickle/jsonpickle#230]
jsonpickle 1.0 was released two weeks ago (2018-09-02):

<img width=70% src=https://user-images.githubusercontent.com/1324225/45612607-38624a00-ba6c-11e8-9a34-c1b808b51391.png>

https://github.com/jsonpickle/jsonpickle/releases

However, the latest version on PyPI is 0.96 (2018-02-09):

![image](https://user-images.githubusercontent.com/1324225/45612586-1e286c00-ba6c-11e8-916d-f82ee0a000be.png)

https://pypi.org/project/jsonpickle/#history

Are there plans to release 1.0 on PyPI?

Thank you.

**Comment by davvid** [comment]
I haven't been able to get pypi working with the new `twine` tools.  I always get authentication errors, even though    my account is valid.  :sigh:.  It worked just fine before they deprecated the old upload workflow.  It's on my todo list to try and update it.  If someone has a working pypi account (@jaraco?) I could grant permission to the project so that someone else can try uploading to pypi.  I'll try again soon.

**Comment by hugovk** [comment]
I have a working PyPI account, but it'd probably be better for an existing team member to do it.

Better still, can we help figure out what's up with twine for you?

I normally do something like this when releasing (although you could probably omit the `wheel` stuff as it looks like jsonpickle doesn't yet make those), it's usually a good start to check the tools are updated:

```sh
pip install -U pip setuptools wheel twine keyring
rm -rf build
python setup.py sdist --format=gztar bdist_wheel
twine upload -r pypi dist/projectname-1.0.0*
```

**Comment by jaraco** [comment]
I'm happy to do an upload. I'm `jaraco` in PyPI. I could also send a PR to have Travis upload the dists after a tagged commit passes, though that may have to wait for another day.

**Comment by davvid** [comment]
hah, I had the wrong password configured this whole time.  I finally got it uploaded after I figured that out.  I've added you as an owner on pypi nonetheless.  `v1.0` is now available on pypi.

**Comment by hugovk** [comment]
Thank you!

Always good to increase the bus factor.

**Comment by jaraco** [comment]
Excellent! Glad to see the 1.0 release.
