### ISSUE TITLE
Release 1.0 has no .whl files for Python 2, and no source files.

### ISSUE THREAD

**Issue by orf** [jsonpickle/jsonpickle#233]
You currently cannot install `jsonpickle==1.0` with Python 2. See here:

https://pypi.org/simple/jsonpickle/

There is a `.whl` file for Python 3, but no source release or `.whl` file that would be compatible with Python 2 :(

This might be related to the issues @davvid was experiencing in #230 

Is this intentional?

**Comment by davvid** [comment]
I just uploaded a source release.  That was a mistake -- I was still adjusting to the new `twine`-based workflow.  Our config now has `universal = 1` too so our `.whl` uploads will be universal only from now on.
