### ISSUE TITLE
cannot pickle Decimal

### ISSUE THREAD

**Issue by JssDWt** [jsonpickle/jsonpickle#244]
jsonpickle serializes Decimal as `null`. 

Steps to reproduce:
- install jsonpickle 1.0 and simplejson 3.16.0 in a python 3.7 environment
- execute the following code:
```python
import jsonpickle
from decimal import Decimal
jsonpickle.set_preferred_backend('simplejson')
jsonpickle.set_encoder_options('simplejson', use_decimal=True)
print(jsonpickle.encode(Decimal('2.0'), unpicklable=False, warn=True))
```
This prints:
> UserWarning: jsonpickle cannot pickle Decimal('2.0'): replaced with None
>   warnings.warn(msg)
> null

**Comment by rafalkasa** [comment]
Please try https://stackoverflow.com/questions/54276418/jsonpickle-with-simplejson-backend-serializes-decimal-as-null

```
import jsonpickle
from decimal import Decimal

jsonpickle.set_preferred_backend('simplejson')
jsonpickle.set_encoder_options('simplejson', use_decimal=True)

class DecimalHandler(jsonpickle.handlers.BaseHandler):

    def flatten(self, obj, data):

        return obj.__str__() #Convert to json friendly format

jsonpickle.handlers.registry.register(Decimal, DecimalHandler)

class MyClass():
    def __init__(self, amount):
        self.amount = amount

    def to_json(self):
        return jsonpickle.dumps(self, unpicklable=False)

if __name__ == '__main__':
    obj = MyClass(Decimal('1.0'))
    print(obj.to_json())
```

**Comment by JssDWt** [comment]
This actually prints `{"amount": "1.0"}`, which is not what I want. I'd expect `{"amount": 1.0}`.

**Comment by woutdenolf** [comment]
Why do you expect a `float`? If you are worried about rounding errors, shouldn't you expect a `str`? Converting to `float` defies the purpose of having `Decimal` in the first place:

```Python
from decimal import Decimal
string = '1.00000000000000000000000001'
decimal = Decimal(string)
assert str(decimal) == string  # OK
assert str(float(decimal)) == string  # NOK
assert float(decimal) == decimal  # NOK
```

**Comment by JssDWt** [comment]
I do not expect a `float`. I expect to create a json value as a number, not a string. json does not interpret the kind of number or the precision. Serializing as a string would cause hassle explaining to other clients they should interpret the string as a number, which is not what I want.
Simplejson is capable of doing what I want and serializes `Decimal` as a json number if `use_decimal` is `True`. I'd expect the same to happen when using jsonpickle with simplejson as a backend.
The example you provide is python specific, and does not have to do much with json numbers.

**Comment by davvid** [comment]
I provided an example in the stackoverflow thread demonstrating how to do this.  Additionally, I added  a new `use_decimal` mode to `encode/dumps` that avoids converting to null and allows simplejson to handle the value rather than getting handled by jsonpickle.

https://jsonpickle.readthedocs.io/en/latest/api.html#jsonpickle.pickler.encode

It sounds like your use case is pretty specific, so please see the S.O. thread for more details.

**Comment by JssDWt** [comment]
@davvid that is excellent. Thank you very much.
