### ISSUE TITLE
Base-85 encode bytes on Python 3.4+?

### ISSUE THREAD

**Issue by dargueta** [jsonpickle/jsonpickle#250]
The `base64` library supports [base-85 encoding](https://docs.python.org/3/library/base64.html#base64.b85encode) as of Python 3.4. This is a more efficient form of text encoding, that bloats binary data by only 1/4 as opposed to base-64 which expands binary data by 1/3. From some manual testing I've done with randomized bytes given by `os.urandom()`, this change makes payloads about 10% smaller.

Given that Python 3.3 has reached end of life and is no longer supported by pip, and Python 2 can't read data pickled by Python 3 anyway, I think it'd be cool if we could add an option to `encode()` to encode binary data using base-85.

As long as we provide this as an additional argument to `encode()`, this would be backwards-compatible and shouldn't break anything (I believe). What do people think?

**Comment by davvid** [comment]
That could be useful.  Is there a python2.7 backport?  If not we can just ignore that flag when the module is unavailable.  It sounds like it'll have to be public state on the Pickler context so that custom handlers can check for it -- base64 is also used by the numpy handler.

**Comment by dargueta** [comment]
> Is there a python2.7 backport?

Judging from the first few pages of search results on PyPI, no.

> It sounds like it'll have to be public state on the Pickler context so that custom handlers can check for it -- base64 is also used by the numpy handler.

How much of a hassle would that be?

**Comment by davvid** [comment]
Actually, python2 jsonpickle can read data pickled by python3 -- that's one of the benefits of a neutral format like json.  We serialize to a python-version-neutral representation for things like `__builtins__`, but in general, yeah, there are modules in python3 that don't exist in python2, and vice-versa.

In any case, we don't make any guarantees about that behavior, and the savings from a smaller representation are worth it, so having it gracefully upgrade itself when running on newer pythons is a good way to go.  Just make sure to document that behavior.

We should still provide an opt-out flag that would become another member variable on the Pickler class.  The unpickler doesn't need any options -- it should be able to know by looking at the data.  It's not much of a hassle, give it try.

**Comment by dargueta** [comment]
Implemented in #251
