### ISSUE TITLE
Dictionary identity not preserved through roundtrip

### ISSUE THREAD

**Issue by andrewbaxter** [jsonpickle/jsonpickle#255]
On jsonpickle 1.1:

```
>>> import jsonpickle
>>> x = {}; y = jsonpickle.decode(jsonpickle.encode([x, x]))
>>> y[0]['hi'] = 3
>>> y[1]
{}
```

I didn't see any warnings about this in the doc and `list`s seem to survive fine.  Adding a custom handler to try to trigger the id serialization didn't work.

Actually, trying with some more mutable builtin types - `set` identity doesn't appear to be preserved either.

This is an important use case for us since we need to serialize user data and can't reasonably request them to prevent duplicate dictionaries in their graphs.

**Comment by davvid** [comment]
We should do a v2 encoder as described in #246.  Preserving dict and set identity would be a welcome addition.  Only atoms like strings and ints should be excluded from the reference detection.

**Comment by davvid** [comment]
Thanks for the report.  A simpler solution was found that preserves dict identity.  Please test out the proposed changes in #342 and let me know if it works for your use case.

I added a test case to `tests/jsonpickle_test.py` that mimics the use case you identified above.  Before the changes that test was failing, and now it passes.  I'm kinda happy that making this change was relatively simple.  e72b5967ca3d5ff283ac8c1e79ce7928ec81d1e2
