### ISSUE TITLE
Crash on circular reference between objects

### ISSUE THREAD

**Issue by rht** [jsonpickle/jsonpickle#264]
Observed at https://github.com/projectmesa/mesa/pull/662#issuecomment-495095834.
I tried to reproduce with a minimal version with
```
class Thing(object): 
     def __init__(self, name, x): 
         self.name = name 
         self.x = x
a = Thing(None, 1)
b = Thing(a, 2)
a.name = b
frozen = jsonpickle.encode(a) 
frozen2 = jsonpickle.encode(b)
```
but this didn't crash. Perhaps @Corvince could explain the bug better.

**Comment by davvid** [comment]
I think I understand what you mean.  We do try to prevent circular references, but the `unpickleable=False` code path might not handle it correctly -- I'll have to double-check if we have a test case for that in our test suite.  Thanks for the report -- I'll try writing a test, but if yall come up with a reproducer please let me know.

**Comment by davvid** [comment]
Thanks for the heads-up.  Your report uncovered an untested edge case.  I added a test case and we now handle this gracefully.  cheers

**Comment by rht** [comment]
Thanks for the speedy resolution!
