### ISSUE TITLE
limit precision of floats

### ISSUE THREAD

**Issue by schwittlick** [jsonpickle/jsonpickle#271]
I am wondering whether there is a way to limit the precision of jsonpickle'd floats and doubles.

**Comment by davvid** [comment]
This would likely have to be a feature in one of the underlying json libraries (e.g. stdlib `json`, `simplejson`, `demjson`, etc.).   If any of them supports this feature then the `set_encoder_options` API can be used to customize the parameters that are passed to the backend.
