### ISSUE TITLE
jsonpickle saving __weakref__ attribute causing decode error.

### ISSUE THREAD

**Issue by leon332157** [jsonpickle/jsonpickle#272]
When using the library to store a [discord.py User Object](https://discordpy.readthedocs.io/en/latest/api.html#user) , it raises an error when decoding `AttributeError: attribute '__weakref__' of 'User' objects is not writable`

**Comment by davvid** [comment]
I suspect that a possible solution would be for jsonpickle to skip the `__weakref__` attribute while encoding, that way the decoder will never run into this error.

`__weakref__` is a deep implementation detail in how weak references are handled in CPython, so I'm going to add some special cases to skip them.

I don't have a way to reproduce the error currently without adding a new dev dependency but I'll try to create a test case that uses weakrefs, or `__slots__` + `__weakref__` to see if it triggers it.

Thanks for the heads-up.

**Comment by leon332157** [comment]
How would I be able to ignore an attribute when encoding using jsonpickle?

**Comment by davvid** [comment]
It would probably have to be done in jsonpickle itself.  There's a part in the encoder where we walk over each key/value dictionary pair.  I've been trying to reproduce this issue (to no avail) so if you have a test case that will speed things along.

**Comment by leon332157** [comment]
Hey, idk if this is still active but this happens when I try to save a discord.py User object.

**Comment by leon332157** [comment]
Also, for a small fix for this problem. I simply added a check to _flattern_obj_attrs in pickler.py.
```py
    def _flatten_obj_attrs(self, obj, attrs, data):
        flatten = self._flatten_key_value_pair
        ok = False
        for k in attrs:
            try:
                if k == '__weakref__':
                    continue
                value = getattr(obj, k)
                flatten(k, value, data)
            except AttributeError:
                # The attribute may have been deleted
                continue
            ok = True
        return ok
```
This resolved my issue, but I'm not sure if this will affect some usage with the weakref module. But since __weakref__ is a reference anyways, I don't think it will affect anything in terms of jsonpickle saving some object attributes.
