### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonpickle' when running tests

### ISSUE THREAD

**Issue by Almenon** [jsonpickle/jsonpickle#277]
The folder structure is like this:
jsonpickle
 \- \_\_init\_\_.py
 \- source code
tests
 \- object_test.py
 \- other tests...

object_test tries to import jsonpickle but it is in the parent directory, not the current directory, so it doesn't find it. How are you able to run the tests?

I was able to run the tests myself before but I forgot how I did it >_<

**Comment by davvid** [comment]
Wow, I didn't realize that we never wrote down the testing instructions.  Please see the README.rst file for the details.  Thanks for the report.

**Comment by Almenon** [comment]
`make test` worked but I want to be able to run tests via VSCode test runner. I switched to unittest discovery instead of pytest discovery and it worked.
