### ISSUE TITLE
Same Enum value as key _and_ value in dict may corrupt data when round-tripping

### ISSUE THREAD

**Issue by torbjorv** [jsonpickle/jsonpickle#286]
Version: Python 3.7.1, jsonpickle 1.2

The below code decodes the second MyEnum.BLUE (the value, not the key) as an instance of MyClass. I've played with mixin str on the enum, keys=False and the issue may go away, but by reorganizing the structure (or making it more complex) I can consistently reproduce again. Below is the simplest reproduce I could come up with.

```python
class MyClass:
    pass


class MyEnum(Enum):
    BLUE = 'blue'


class TestJsonPickle(unittest.TestCase):

    def test_bug(self):

        expected = {
            'first': MyClass(),
            MyEnum.BLUE: MyEnum.BLUE
        }

        actual = jsonpickle.decode(jsonpickle.encode(expected, keys=True), keys=True)

        print(expected)
        print(actual)
```

expected:
```
{ 
    'first': <test_jsonpickle.MyClass object at 0x101e63400>,
    <MyEnum.BLUE: 'blue'>: <MyEnum.BLUE: 'blue'>
}
```

actual:
```
{ 
    'first': <test_jsonpickle.MyClass object at 0x101eb57f0>,
    <MyEnum.BLUE: 'blue'>: <test_jsonpickle.MyClass object at 0x101eb57f0>
}

```

**Comment by davvid** [comment]
If you have keys that are non-strings then you need to pass `keys=True` to both `encode()` and `decode()` (aka dumps / loads).  The commit above added this use case to the test suite, and it demonstrates how to use it.

**Comment by davvid** [comment]
Sorry, I see the issue now.  I'll had to adjust the test to say `first` and then it started reproducing.

**Comment by davvid** [comment]
Thanks for the report.  I added a couple of test cases to cover this use case so this should be supported going forward.  Let me know if that does the trick for you.

**Comment by torbjorv** [comment]
This looks good to me, thanks for taking care of this!
