### ISSUE TITLE
TypeError: keys must be a string

### ISSUE THREAD

**Issue by Almenon** [jsonpickle/jsonpickle#287]
Jsonpickle fails when trying to encode a series with a Hierarchical index

callstack: https://i.imgur.com/SswLYZW.png
variables: https://i.imgur.com/ApMsT24.png

Reproduction code:
```python
import jsonpickle

import pandas as pd
lets = ['A', 'B', 'C']
nums = ['1', '2', '3']
midx = pd.MultiIndex.from_product([lets, nums])
units = pd.Series(0, index=midx)

import jsonpickle.ext.pandas as jsonpickle_pandas
jsonpickle_pandas.register_handlers()

jsonpickle.encode(units)
```

result:

```
>>> jsonpickle.encode(units)
C:\dev\AREPL-backend\python\jsonpickle\ext\pandas.py:100: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  dtypes = {k: str(pd.np.dtype(type(obj[k]))) for k in obj.keys()}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\AREPL-backend\python\jsonpickle\pickler.py", line 101, in encode
    return backend.encode(context.flatten(value, reset=reset))
  File "C:\dev\AREPL-backend\python\jsonpickle\backend.py", line 169, in encode
    raise e
  File "C:\dev\AREPL-backend\python\jsonpickle\backend.py", line 166, in encode
    return self.backend_encode(name, obj)
  File "C:\dev\AREPL-backend\python\jsonpickle\backend.py", line 177, in backend_encode
    return self._encoders[name](*encoder_args, **encoder_kwargs)
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python38-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\almenon\AppData\Local\Programs\Python\Python38-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
```

Note that if you don't register the pandas handler jsonpickle will work correctly. Therefore I'm assuming this is a bug with the pandas handler.

Also note non-hierarchial indexes work fine. For example, if your replaced the `units` line with `units = pd.Series(0, index=[1,2,3])` you would not get an error.

Thanks to @mccannjb for reporting

**Comment by Almenon** [comment]
@parsons-kyle-89 @rfdougherty FYI

Letting you know in case you want to take a crack at it, otherwise I might get to it eventually.

**Comment by davvid** [comment]
I accidentally commented on the other issue.  This is working correctly now.  I added the example above to the test suite so this should be working correctly now, but please let me know if you're seeing otherwise.

**Comment by davvid** [comment]
6f5c30c6fec5a80c98c1a64609b34d3f19ad12b2 is the commit that actually fixed it.  That commit accidentally mentioned the issue number from the AREPL-vscode so it didn't close this one.

**Comment by Almenon** [comment]
it works, thanks! :D
