### ISSUE TITLE
Security compared to pickle too hard to find

### ISSUE THREAD

**Issue by hartwork** [jsonpickle/jsonpickle#294]
Hi!

I tried to find an answer if jsonpickle has the same design security issues that pickle has. I found #179 eventually but it took a while and there is nothing like in the master readme, the place where I'd expect security implications as severe as that. Would you be up for adding a warning to some place clearly visible in the readme?

Thanks for your consideration, Sebastian

**Comment by davvid** [comment]
FWIW it is mentioned on the documentation landing page:

https://jsonpickle.readthedocs.io/en/latest/#module-jsonpickle

Please feel free to open with a PR to update the README with a similar warning.

Thanks for the heads-up.

**Comment by hartwork** [comment]
> FWIW it is mentioned on the documentation landing page:
> 
> https://jsonpickle.readthedocs.io/en/latest/#module-jsonpickle

I would pull it up and out of `jsonpickle Usage` into `jsonpickle Documentation` before the table of contents but it's great to have already.


> Please feel free to open a PR to update the README with a similar warning.

I have created #295 for that now.

**Comment by hartwork** [comment]
@davvid thank you! :+1:
