### ISSUE TITLE
Tags should be configurable

### ISSUE THREAD

**Issue by MicheleMannino** [jsonpickle/jsonpickle#298]
I'd like to configure internal tags (contained into jsonpickle/tags.py):

e.g.

`OBJECT = 'py/object'    # OBJECT = 'py_object'`
`TYPE = 'py/type'    # TYPE = 'py_type'`

because the **/** char could be a problem on deserializing again to other languages, such as Java.

**Comment by davvid** [comment]
From the implementation perspective: for better or worse python is a monkeypatch-friendly language.

If you import the `jsonpickle.tags` module and change the corresponding variables then the rest of the implementation should work as expected.

I'd be happy to document this as part of the public API, with the understanding that you're in control of `main()` so you have the ability to set this up before using jsonpickle.

If any code is relying on stuff not defined by that module then that is considered a bug.  You will have to redefine `RESERVED` yourself as well.

**Comment by davvid** [comment]
Curious, why would the "/" be a problem?  Can Java not store strings in hash table keys that contain `/`?
