### ISSUE TITLE
New PyPI release to include indent kwarg in encode

### ISSUE THREAD

**Issue by Lightslayer** [jsonpickle/jsonpickle#299]
Hi, it appears that the current PyPI release (version 1.3 from Feb 2020) does not include the latest changes to `encode` enabling the use of the `indent` keyword argument from #183.

As such, would it be possible to get a new release pushed so that this can be included and so that developers do not need to rely on using the latest master (which is subject to change) via `pip install git+https://github.com/jsonpickle/jsonpickle`?

**Comment by davvid** [comment]
Resolved in v1.4
