### ISSUE TITLE
Fails to Load 1.4 due to meta data issues.

### ISSUE THREAD

**Issue by DavidWylie** [jsonpickle/jsonpickle#300]
Im using the library as part of aws xray sdk in an aws lambda environment on pythion 3.8.
When importing the latest version gives the following error.

Ive included a cut down stack trace below.
Affected version jsonpickle 1.4  when forcing a 1.3 release it works correctly.

`
[ERROR] PackageNotFoundError: importlib_metadata

...

 File "/var/task/jsonpickle/__init__.py", line 64, in <module>
    from .version import __version__  # noqa: F401
  File "/var/task/jsonpickle/version.py", line 2, in <module>
    import importlib_metadata as metadata
  File "/var/task/importlib_metadata/__init__.py", line 602, in <module>
    __version__ = version(__name__)
  File "/var/task/importlib_metadata/__init__.py", line 564, in version
    return distribution(distribution_name).version
  File "/var/task/importlib_metadata/__init__.py", line 537, in distribution
    return Distribution.from_name(distribution_name)
  File "/var/task/importlib_metadata/__init__.py", line 205, in from_name
    raise PackageNotFoundError(name)
`

**Comment by davvid** [comment]
Thanks for the heads-up.  I had put try/excepts around this part in case we got issues from the external dependency and it looks like that's happening here.

What version do you get when you run `pip freeze | grep importlib_metadata` in your environment?

```
importlib-metadata==1.5.0
```
Is what I have here.  I already have a try/except -- I didn't want to make it blind, but I might as well just catch `Exception` now.

**Comment by davvid** [comment]
This is weird.  We already capture `ImportError` and in every environment I've checked the `PackageNotFoundError` exception has `ImportError` in its `PackageNotFoundError.mro()` method resolution order (meaning, it should be getting caught already.

If you're able to tweak the modules, does changing the try/except bits in `jsonpickle/version.py` to `except Exception:`  instead of `except ImportError:` and `except (AttributeError, ImportError):` in there make a difference?

I'm trying to understand why the exception handling in there isn't catching this one.  Do you have an easy way for me to reproduce it so that I can know that it's going to be fixed?

**Comment by DavidWylie** [comment]
Sorry ive not found a way to reproduce this outside of a serverless application in an aws lambda.

But i did find a possibility that might explain how this is getting around the error handling in jsonpickle.  Looking at the code PackageNotFoundError. might not be child of ImportError but could be child of FileNotFoundError.  

class PackageNotFoundError(ModuleNotFoundError):
    """The package was not found."""

and from  _compat.py

try:
    ModuleNotFoundError = builtins.FileNotFoundError
except (NameError, AttributeError):  # pragma: nocover
    ModuleNotFoundError = ImportError  # type: ignore


So catching file not found or PackageNotFoundError in addition to the import error should catch it.

**Comment by DavidWylie** [comment]
sorry im not able to edit the module in the environment im seeing the problem in. due to the build process on my side.

**Comment by davvid** [comment]
Excellent, thanks for the details about the exceptions.  This warrants a patch release.

**Comment by davvid** [comment]
`FileNotFoundError` is a Python3-only exception, and In Python3.8 `FileNotFoundError` derives from `OSError`.  It looks like a simple solution will be to add `OSError` to the set of exceptions we're catching in `jsonpickle/version.py`.  I'll give that a try.

I'll respond here once `v1.4.1` has been deployed.

**Comment by davvid** [comment]
jsonpickle 1.4.1 is now available via `pip`.  Thanks for the heads-up!
