### ISSUE TITLE
Use importlib.metadata from the standard library on Python 3.8+

### ISSUE THREAD

**Issue by hroncok** [jsonpickle/jsonpickle#303]
Hello. Would you accept a pull request that uses `importlib.metadata` from the standard library on Python 3.8+ instead of the `importlib_metadata` package?

If so, do you prefer `try: import importlib.metadata, except: import importlib_metadata` or `if version < 3.8` approach?

Examples:

 - https://github.com/pytest-dev/pytest/pull/5539
 - https://github.com/pytest-dev/pluggy/pull/223
 - https://github.com/tox-dev/tox/pull/1368

**Comment by davvid** [comment]
That sounds great.  I prefer the explicit version checks.  I've used import checks before for stuff in `builtins` before but they were defeated when I had the futurize modules installed in a different environment, so now I'm battle scarred and prefer the explicit checks whenever possible.

Also, in case it helps, our project skeleton is based on https://github.com/davvid/skeleton/ the python2.7-compat branch.  If it's a file that's common to the skeleton I'll take the change there and then merge it into here.

**Comment by hroncok** [comment]
https://github.com/davvid/skeleton/search?q=importlib_metadata&unscoped_q=importlib_metadata yields nothing (I've manually checked setup.cfg as well)

**Comment by hroncok** [comment]
https://github.com/jsonpickle/jsonpickle/pull/305
