### ISSUE TITLE
Cannot encode objects with both __dict__ and __slots__

### ISSUE THREAD

**Issue by yck011522** [jsonpickle/jsonpickle#306]
Hi all. (excuse me if I'm rather new to jsonpickle)

I have my classes that have both _dict__ and __slots__. Trying to get the best of both worlds. A simple example below:

```
import jsonpickle

class MyBrokenPoint(object):
    __slots__ = ['_x', '_y', '_z', '__dict__']
    
    def __init__(self, x, y, z):
        self._x = 0.0
        self._y = 0.0
        self._z = 0.0

my_point = MyBrokenPoint(1,2,3)

print ((jsonpickle.encode(my_point, warn = True, indent = 4, keys = True)))
print(my_point.__slots__)
print(my_point.__dict__) 
```
Output
```
{
    "py/object": "__main__.MyBrokenPoint"
}

['_x', '_y', '_z', '__dict__']

{}
```

Notice that the '_x', '_y', '_z' attributes are not encoded :(

**Expected Behaviour**

The '_x', '_y', '_z' attributes exist in the encoded string

**Comment by yck011522** [comment]
For background information, I'm using the [compas](https://compas-dev.github.io/main/) geometry framework. I've also opened a [ticket ](https://github.com/compas-dev/compas/issues/525)on that side. But I believe this issue is more related to jsonpickle.

**Comment by ZENALC** [comment]
Not sure if I'm right, but why would you use __dict__ with slots? Doesn't that defeat the whole purpose of it?

Also, since __dict__ just returns an empty dictionary (as shown from your example), what is the purpose of it?

**Comment by yck011522** [comment]
@ZENALC I believe you are right. I'm not sure. 

But compas-dev accept my PR to remove that empty __dict__ to their classes. So the problem is solved for me. So I'm closing this issue.

However, whether it make sense to have both __dict__ and __slots__ is beyond my knowledge. I assume read/write access to the slots are still much faster even in the presence of a __dict__. And the __dict__ gives flexibility to dynamic assignment.
