### ISSUE TITLE
please indicate which GPG key is expected to sign pypi releases

### ISSUE THREAD

**Issue by FelixSchwarz** [jsonpickle/jsonpickle#310]
Thank you very much for signing your pypi releases. I'll try to make sure that the Fedora (+ CentOS/EPEL) RPM build process will verify the source code whenever a new version is built.

However it would be really helpful if there was an indication which GPG key(s) are expected to sign releases (ideally I'd like to retrieve these keys via a HTTPs URL directly).

**Comment by davvid** [comment]
My gpg is available here.

https://keys.openpgp.org/search?q=davvid%40gmail.com

Thanks for setting this up!

**Comment by FelixSchwarz** [comment]
Thank you.

Just to be sure: Your key id is `FA41 BF59 C1B4 8E8C 5F3D A61C 8CE2 6BF4 A9F6 06B0` ?

**Comment by davvid** [comment]
Yes, that's the one.

**Comment by musicinmybrain** [comment]
I found https://github.com/Theelx.gpg. That seems to work.

**Comment by musicinmybrain** [comment]
Thanks!
