### ISSUE TITLE
Dictionaries with object keys are not encoded properly

### ISSUE THREAD

**Issue by jauerb** [jsonpickle/jsonpickle#314]
Instead of being encoded as objects they are encoded as strings using the object's repr. 

Here's a minimal example.  Retrieving with my object key from the original dictionary works fine, but in the dictionary loaded form jsonpickle, that raises a KeyError, and need to use the repr as key, which is unexpected.

```
import jsonpickle

class MyClass:
    def __init__(self, value):
        self.value = value
        
    def __repr__(self):
        return f'{self.__class__.__name__}({self.value})'
    
    def __hash__(self):
        return hash(repr(self))
    
    def __eq__(self, other):
        try:
            return self.value == other.value
        except AttributeError:
            return False
        
obj = MyClass(42)
dictionary = {obj: obj.value}
encoded_string = jsonpickle.dumps(dictionary)
decoded_dictionary = jsonpickle.loads(encoded_string)
print('Retrieving from dictionary')
print('using object key', dictionary[obj])


print('Retrieving from decoded_dictionary')
try: 
    print('using object key', decoded_dictionary[obj])
except KeyError:
    print('KeyError when using object key')
    
print('using repr key', decoded_dictionary[repr(obj)])
```

output:

```
Retrieving from dictionary
using object key 42
Retrieving from decoded_dictionary
KeyError when using object key
using repr key 42

```

**Comment by davvid** [comment]
Hello, this already works, and is supported.

https://jsonpickle.readthedocs.io/en/latest/api.html#jsonpickle-high-level-api

We keep getting issues about this feature where people don't know that they need to pass `keys=True` to `loads` and `dumps` in order to use this feature.  That tells me that the documentation needs to lift this feature up to the top-level and make it easier to find.

I think we should add a top-level example to the docs that basically demonstrates this use case.  Thus, I'm going to leave this issue open until the docs are updated.

**Comment by davvid** [comment]
BTW, did you read the docs at all before using the library?  Would improving the docs help future users discover this more easily?  I'm curious whether or not you saw the documentation at all, or if there's another mechanism that you use to learn about the code.

Thanks for the heads-up.  My take on this is we need to improve something to make these details more discoverable, so I just want to make sure that the "jsonpickle Usage" section on front page of the docs https://jsonpickle.readthedocs.io/en/latest/ is the right place.

**Comment by jauerb** [comment]
Thanks for the prompt response!!!   

Sorry, I was not aware of that option.  Could you explain why that is not the default behavior?  As that would have been my expectation.

I did read some of the docs, but did not look deeply enough to discover this option.  I do think adding it to the front page of the docs might be helpful, especially if this has come up numerous time.

**Comment by davvid** [comment]
Thanks for the sug.  This now on the front page, and includes an explanation ;-)

https://jsonpickle.readthedocs.io/en/latest/#jsonpickle-usage
