### ISSUE TITLE
Document stdlib json module method compatibility 

### ISSUE THREAD

**Issue by techdragon** [jsonpickle/jsonpickle#315]
The code currently includes this little snippet which isn't mentioned in the documentation.https://github.com/jsonpickle/jsonpickle/blob/25ea6c23c9d6ef0899f4143db3dbad19733cf58a/jsonpickle/__init__.py#L83-L85 It's worth calling this out since compatibility is a useful property. 😄

**Comment by Theelx** [comment]
I think that the ideal program depending on jsonpickle would not use these aliases, as people could always do:
```
from jsonpickle import encode as dumps, decode as loads
```
if absolutely necessary for compatability reasons. People should really use encode and decode though to disambiguate as to whether the oft-used json library or jsonpickle is doing the (de)serialization.

I'm going to close this as won't fix, and I'll probably remove those aliases in jsonpickle 3.0, unless people complain.
