### ISSUE TITLE
Big list was encoded into {'py/id':4}

### ISSUE THREAD

**Issue by AlexLuya** [jsonpickle/jsonpickle#323]
**My configuration:**
jsonpickle==1.4.1
Python 3.8.5
ubuntu 20.04 64bit

I have a class with structure like this:
`{"key":[object1,....]}`
each object has a list attribute name "backbones",some of them is small like:
`['CCNet'],['CSPNet','ResNet18']....`
Some of them have a big list like:
`['densenet121', 'resnext101_64x4d', 'xception', 'se_resnext50_32x4d', 'resnet18', 'fbresnet152', 'vgg16_bn', 'timm-efficientnet-b8', 'timm-efficientnet-b2', 'squeezenet1_0', 'efficientnet-b6', 'resnet152', 'vgg16', 'efficientnet-b7', 'timm-efficientnet-b6', 'bninception', 'resnext101_32x16d', 'dpn131', 'densenet201', 'resnext101_32x48d', 'vgg13_bn', 'efficientnet-b1', 'dpn68b', 'timm-efficientnet-b7', 'efficientnet-b0', 'mobilenet_v2', 'resnext101_32x4d', 'vgg13', 'se_resnet152', 'inceptionresnetv2', 'resnet101', 'dpn68', 'densenet161', 'timm-efficientnet-b3', 'polynet', 'timm-efficientnet-b0', 'timm-efficientnet-b5', 'pnasnet5large', 'timm-efficientnet-l2', 'efficientnet-b3', 'nasnetamobile', 'efficientnet-b5', 'resnet34', 'vgg19_bn', 'resnext101_32x32d', 'densenet169', 'se_resnext101_32x4d', 'senet154', 'nasnetalarge', 'se_resnet50', 'inceptionv4', 'timm-efficientnet-b1', 'alexnet', 'squeezenet1_1', 'dpn92', 'resnext50_32x4d', 'resnext101_32x8d', 'dpn98', 'resnet50', 'dpn107', 'vgg19', 'efficientnet-b2', 'inceptionv3', 'se_resnet101', 'vgg11_bn', 'efficientnet-b4', 'cafferesnet101', 'vgg11', 'timm-efficientnet-b4']
`
By using jsonpickle.encode(),small list can be encoded into dict properly,but all attributes with above big list as values were encode into {'py/id':4},can anyone tell me why?

**Comment by talmachani** [comment]
I think this means that the list was already appeared, make_ref is True by default.
jsonpickle will make a reference to object that were already encoded.

**Comment by davvid** [comment]
Yup.  The ref identifiers are used to reconstruct the python object structure exactly as it originally appeared.  That means if you have the same list referenced from multiple sub-objects then it will be encoded only once and then further entries in the stream will have reference IDs referring to the same list.

When using `decode()` to reconstruct the object it'll build only a single list and then add references to it when it encounters the `py/id` entries.  `make_refs=True` is the feature that allows us to reconstitute objects with cyclical references and has the nice side-effect of making the resulting json more compact.

Hope that helps.
