### ISSUE TITLE
make_refs=False Not working as expected or breaking the _in_cycle

### ISSUE THREAD

**Issue by talmachani** [jsonpickle/jsonpickle#333]
So reviewing a few issues here I feel like that some are originated from the root cause which is that _in_cycle reference if not working properly when make_ref is false.

First, here is a simple script of how to reproduce the issue fast and easy.

```python
import datetime
from pprint import pprint

import jsonpickle
import pytz

d1 = datetime.datetime(2020, 6, 6, 6, 6, 6, 6, tzinfo=pytz.UTC)
d2 = datetime.datetime(2020, 6, 6, 6, 6, 6, 6, tzinfo=pytz.UTC)
l = [d1, d2]
encoded_list = jsonpickle.encode(l, make_refs=False)
pprint(encoded_list)
decoded_list = jsonpickle.decode(encoded_list)
```

I have been doing some investigation, the issue happens only when `make_refs=False`. 
and source of it is in the `_in_cycle` method, specifically this condition `(not make_refs and id(obj) in objs)` something is not right here.

As per my understanding when flatten is called for object if it will have the same ID so objs will contain him so _in_cycle will return true and `repr` will be called.

**Comment by davvid** [comment]
I have a solution for this -- it's the same as the solution for #334 and #337 and seems to be working out so I'm going to push a `refs` branch to my `davvid` fork so we can test it out.

Please try it out and let me know if that works for you.  Please see #338 for the proposed solution.
