### ISSUE TITLE
Inconsistent encoding of objects in a list

### ISSUE THREAD

**Issue by Almenon** [jsonpickle/jsonpickle#334]
After the fourth object the encoding strategy differs - see https://github.com/Almenon/AREPL-backend/issues/163

Is there a reason for this? I'm not sure if it's intentional or not.

**Comment by davvid** [comment]
Please test the proposed changes in #338 and let me know if it fixes things for your use case.

**Comment by Almenon** [comment]
Now the encoding strategy is consistent, thanks!
