### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Theelgirl** [jsonpickle/jsonpickle#350]
I have a benchmark plugin for pytest and I've written about 25-30 tests to measure performance of various types of encoding and decoding across jsonpickle 0.9.6 (last pre-stable), 1.4.0 (before all the optimizations in 1.5 series), and 1.5.2 (most recent) on Python 3.9.1. Can I submit the tests and the results as a PR @davvid?

**Comment by davvid** [comment]
That sounds pretty cool, it'd be great to see the same benchmarks you were using.  I've sorted out the semver release snafu so we're good to start taking PRs again.  Thanks again!

**Comment by Theelgirl** [comment]
Ok got it. I'll add the .py file I use along with the instructions for use commented at the top, as I'm not sure how to integrate it with tox.

**Comment by davvid** [comment]
Oops, this should have been closed in 3b362382411c9054ac587dfe5acce2377f4228ca but I accidentally entered the wrong issue number.
