### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [jsonpickle/jsonpickle#355]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine jsonpickle/ext/numpy.py, jsonpickle/ext/pandas.py and observe `compresion`, however expect to see `compression`.
- Examine tests/jsonpickle_test.py and observe `typle`, however expect to see `type`.
- Examine docs/api.rst and observe `prefered`, however expect to see `preferred`.
- Examine jsonpickle/pickler.py and observe `examplar`, however expect to see `exemplar`.
- Examine docs/contrib.rst and observe `enivornment`, however expect to see `environment`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/jsonpickle/pull/new/bugfix_typos

Thanks.

**Comment by davvid** [comment]
Yes, @timgates42 please create the PR. Thank you for making these contributions, much appreciated.

**Comment by timgates42** [comment]
Thanks @davvid - done
