### ISSUE TITLE
Pandas list value not decoding properly

### ISSUE THREAD

**Issue by brandonschabell** [jsonpickle/jsonpickle#358]
When decoding a Pandas Dataframe which contains a list value, it is being decoded as a string.

```python
import jsonpickle
import jsonpickle.ext.pandas as jsonpickle_pandas

jsonpickle_pandas.register_handlers()

df = pd.DataFrame({'col1': [[1, 2, 3], ['a', 'b', 'c']]})
assert type(df['col1'].iloc[0]) == list
data = jsonpickle.encode(df)
result = jsonpickle.decode(data)
assert type(result['col1'].iloc[0]) == list  # AssertionError: assert <class 'str'> == <class 'list'>
```

**Comment by losito105** [comment]
Hello! I'm just getting started with open source but I've used jsonpickle before and I'd like to attempt to resolve this issue.

**Comment by losito105** [comment]
I am new to open source contribution, but I've worked with both jsonpickle and pandas in the past and I'd like to try to tackle this issue.
