### ISSUE TITLE
Encoding and decoding of object with append and __getitem__ method results in duplicated list entries

### ISSUE THREAD

**Issue by gschwaer** [jsonpickle/jsonpickle#362]
Hello,
I just found out that objects of a class I wrote are decoded to have duplicated elements in a member list. Thanks to TDD I realized that in one of the test cases. But this came as quite a surprise for me.
Here is a minimal code example:
```python
import jsonpickle

class SomethingList:
    somethings: list

    def __init__(self):
        self.somethings = []

    def append(self, smth: int):
        self.somethings.append(smth)

    def __getitem__(self, i: int) -> int:
        return self.somethings[i]


sl = SomethingList()
sl.somethings.append(1)
print(len(sl.somethings))

ts = jsonpickle.encode(sl)
print(ts)

s2 = jsonpickle.decode(ts)
print(len(s2.somethings))
```
Which prints for me:
```json
1
{"py/object": "__main__.SomethingList", "somethings": [1], "py/seq": [1]}
2
```

If I remove either the `append` method or the `__getitem__` method, I get:
```json
1
{"py/object": "__main__.SomethingList", "somethings": [1]}
1
```

With both methods present, for some reason `"py/seq": [1]` is added in `encode` and when decoding the element in the list is duplicated. No warnings, no exceptions.

This bug might be related to #132.

**Comment by gschwaer** [comment]
I think I found the culprit: In the pickler [it is checked](https://github.com/jsonpickle/jsonpickle/blob/09e88e7b40482fffbfdc3021d27ed009856b1a04/jsonpickle/util.py#L251) if the object is a subclass of a sequence type or if it is "_list like_":
```python
return (
        hasattr(obj, '__class__')
        and (issubclass(obj.__class__, SEQUENCES) or is_list_like(obj))
        and not is_sequence(obj)
    )
```
That is [determined by a check](https://github.com/jsonpickle/jsonpickle/blob/09e88e7b40482fffbfdc3021d27ed009856b1a04/jsonpickle/util.py#L354) for the two above mentioned functions:
```python
return hasattr(obj, '__getitem__') and hasattr(obj, 'append')
```
I think (but didn't check yet) this "like a list" is not reflected in the unpickler, so he treats it exactly like a list, which it might not be. I don't know why this check for list like object is in place. Can it be removed?

**Comment by Theelx** [comment]
It may be able to be removed, I'll run the tests as soon as I can. I think a better solution would be to make the unpickler treat this "like a list" case the same way as the pickler, but if that falls through then I think removing the special case treatment could work instead.

**Comment by Theelx** [comment]
I'm looking back at this, and I think you're right in that we can remove `is_list_like`. It may break API compatibility in some cases, but we could always add a deprecation warning in such cases, and I don't think a use case depending on this behavior is valid anyway. Sorry for taking so long, I was dealing with finals and various other stuff through January and February!

**Comment by gschwaer** [comment]
Hi, no worries. I actually refactored my code a little so the list like check is not hit anymore. So for me it's ok the way it is. Just that `unpickle(pickle(o)) != o` in this case might make someone trip over in the future. Thanks for your efforts!
