### ISSUE TITLE
incorrect serialization of complex object containing sklearn instances

### ISSUE THREAD

**Issue by marekkosta** [jsonpickle/jsonpickle#366]
Hello there.

During our usage of jsonpickle library in combination with sklearn model training and (de)serialization we came across an object, which jsonpickle cannot correctly serialiaze and deserialize. More specifically: An object in memory shows correct behavior while in memory, but it's ill-built and its behavior is buggy after serialization and deserialization.

Looking through open issues this seems to be related to issue #181
The only difference to our case is that we work with the default setting `make_ref=False`.

Our code:

```python
import jsonpickle
import jsonpickle.ext.numpy as jsonpickle_np
import jsonpickle.ext.pandas as jsonpickle_pd
from typing import Text, Any
from sklearn.pipeline import Pipeline


def json_unpickle(file_name: Text) -> Any:
    jsonpickle_np.register_handlers()
    jsonpickle_pd.register_handlers()
    with open(file_name, "r", encoding="utf-8") as f:
        return jsonpickle.loads(f.read())


def json_pickle(file_name: Text, obj: Any) -> None:
    jsonpickle_np.register_handlers()
    jsonpickle_pd.register_handlers()
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(jsonpickle.dumps(obj, indent=1))


class WrappedModel:
    def __init__(self, pipeline: Pipeline):
        self.pipeline = pipeline
        self.classes_ = self.pipeline.classes_


# load sklearn pipeline components
vectorizer = json_unpickle("vectorizer.json")
sgd = json_unpickle("sgd.json")
# build a WrappedModel instance
sklearn_pipeline = Pipeline(steps=[vectorizer, sgd])
wrapped_model = WrappedModel(pipeline=sklearn_pipeline)
print("output:")
print(wrapped_model.classes_)
# pickle & unpickle
json_pickle("model.json", wrapped_model)
wm = json_unpickle("model.json")
print("output after serialization + deserialization:")
print(wm.classes_)
```

Outputs:
```
$ python ./run.py
output:
['i_goodbye' 'i_greet' 'i_how_are_you' 'i_my_name_is' 'i_nice_day' 'i_no'
 'i_restart' 'i_select_animal' 'i_swearing' 'i_thanks' 'i_unsupported'
 'i_who_are_you' 'i_yes']
output after serialization + deserialization:
[[-4.6257104 ]
 [-3.24113826]
 [-3.22166714]
 [-3.57920356]
 [-2.45528723]
 [-2.56593293]
 [-3.75261252]
 [-2.61424524]
 [ 9.18493755]
 [-4.17989477]
 [-4.02656936]
 [-4.08638535]
 [-4.06015507]]


$ pip list
Package         Version
--------------- -------
joblib          1.1.0
jsonpickle      2.0.0
numpy           1.21.3
pandas          1.3.4
pip             21.3.1
python-dateutil 2.8.2
pytz            2021.3
scikit-learn    0.24.2
scipy           1.7.1
setuptools      58.3.0
six             1.16.0
threadpoolctl   3.0.0
wheel           0.37.0

$ python
Python 3.8.12 (default, Sep 10 2021, 00:16:05)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

$ uname -a
Linux abc 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

This behavior was observed on an ubuntu linux machine (all above outputs), but we were able to reproduce the same buggy behavior in a mac os environment: python 3.8, with the same python packages installed as mentioned above.

**Important:** Please download [files.zip](https://github.com/jsonpickle/jsonpickle/files/7409094/files.zip) mentioned in the code to reproduce the bug.

Random, but relevant notes:
- It was very difficult to construct a sensible minimal example. Unfortunatelly, we were not able to get rid of the two .json files: `vectorizer.json` + `sgd.json`
- `vectorizer.json` + `sgd.json` do not contain binary-encoded stuff, so they are safe to import in other environments to reproduce the buggy behavior.
- We investigated the objects in `vectorizer.json` + `sgd.json` and we observed only correct behavior with them, i.e., their (de)serialization does not change them and we obtain the same object by construction "in memory", "the ordinary python way" as by deserializing them from files `vectorizer.json` + `sgd.json`.
- Indeed, it seems that the `"py/id": 37` in the output `model.json` is not computed correctly. We were able to "point it" to the correct object (= the array of strings) by setting `"py/id": 35`. Interestingly, this suggests that the index is "off by 2" instead of "off by 1" as mentioned in issue #181
- We observed the same buggy behavior with version `jsonpickle ==1.5.2`.

**Comment by Theelx** [comment]
I appreciate the detailed report, it makes debugging a lot easier! Have you tried this on jsonpickle==1.5.1? A lot of people have been having issues with 1.5.2 and 2.0.0, so I'm working on solving that now (as I only noticed people having issues a few days ago). If this works on 1.5.1, I suspect it may have the same cause as #364, and if so, I believe I have a fix for it.

**Comment by marekkosta** [comment]
Hello there,

Running the script with versions `1.4`, `1.4.1`, `1.4.2`, `1.5.0`, `1.5.1`, and `1.5.2`. Exhibits the same error behavior. Precise output for the version `1.5.1` follows:

```
$ python ./run.py 
output:
['i_goodbye' 'i_greet' 'i_how_are_you' 'i_my_name_is' 'i_nice_day' 'i_no'
 'i_restart' 'i_select_animal' 'i_swearing' 'i_thanks' 'i_unsupported'
 'i_who_are_you' 'i_yes']
output after serialization + deserialization:
[[-4.6257104 ]
 [-3.24113826]
 [-3.22166714]
 [-3.57920356]
 [-2.45528723]
 [-2.56593293]
 [-3.75261252]
 [-2.61424524]
 [ 9.18493755]
 [-4.17989477]
 [-4.02656936]
 [-4.08638535]
 [-4.06015507]]

$ pip list
Package         Version
--------------- -------
joblib          1.1.0
jsonpickle      1.5.1
numpy           1.21.5
pandas          1.3.4
pip             21.3.1
python-dateutil 2.8.2
pytz            2021.3
scikit-learn    0.24.2
scipy           1.7.3
setuptools      60.0.4
six             1.16.0
threadpoolctl   3.0.0
wheel           0.37.1

$ python
Python 3.8.12 (default, Sep 10 2021, 00:16:05) 
[GCC 7.5.0] on linux

$ uname -a
Linux xumm 5.4.0-91-generic #102~18.04.1-Ubuntu SMP Thu Nov 11 14:46:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I hope this helps.

**Comment by Theelx** [comment]
Oh ok. I suspect this has always been an issue, as it's seemingly complex and I don't believe the sk-learn code has been changed in a while. I'll do what I can to fix it ASAP, but I'm not familiar at all with sk-learn nor jsnpickle's serialization of it, so it may take a while.

And yeah, your detailed information is extremely helpful! Thank you so much for the relevant notes and versions tested, plus the related issue!

**Comment by Theelx** [comment]
I've been working on this for a few hours, and I've found that when using the code from the current main branch, it properly serializes/deserializes as long as ``make_refs=False`` is set when using ``jsonpickle.dumps``. jsonpickle breaking when ``make_refs=True`` is clearly unintended, however I'm not sure of how to fix it in that case (and setting ``make_refs=False`` to the default would break backwards-compatibility, so we can't change the default until 3.0).

I'm leaning towards just adding a note to the ``make_ref`` documentation that says "Setting this parameter to False may fix issues when serializing certain objects, such as sklearn instances." What do you think?

**Comment by marekkosta** [comment]
I'm aware of the fact that `make_refs=False` kind of "solves" the problem, but it is more of an eye wash than a real solution. My ideas regarding this are:
1. Changing the default value is not a good idea at all. Because it can cause serious and very peculiar bugs: something, which was id()-style equal will be only ==-style equal... It seems to me that this can really mess things up - some code working with a original object can completely break down after deserialization, because it relies on specific of the objects and their interlinking (e.g. some graph algorithm code or something like that could be candidates). What do you think?
2. Adding a comment: "always use `make_refs=False` when you don't rely on having the same internal structure of object, i.e., ==-style equality is ok for you and your code does not rely on id()-style equality".
3. Are there any "bad" serializations known, where something sklearn-ish is involved? I don't know the jsonpickle implementation, but were you able to somehow figure out what the role of sklearn in all this is? Is it possible that we could generate a smaller example without it, analyze the serialization algorithm and see why it computes an incorrect reference index?

**Comment by Theelx** [comment]
1. Yeah, I think that's definitely a good reason not to change the default.
2. Yeah I'll make a PR that adds a note like that to the docs. I'm thinking
> "It's recommended to set this parameter to ``False`` when your code does not rely on two objects having the same ``id()`` value and those two objects being equal using ``==`` is sufficient, such as when serializing sklearn instances. If you experience serialization/deserialization being incorrect when you use numpy/pandas/sklearn handlers, this should be set to ``False``."

3. Based on the code in #181, it seems to me that the only other bad serialization was when using numpy. However, the codebase for pyEMMA is too complex for me to understand sadly. My guess is that serialization works fine without numpy/pandas/sklearn though. The issue could be related to the fact that all three of those libraries use a lot of C-extensions, which are notoriously hard to work with in a lot of cases.
