### ISSUE TITLE
jsonpickle.decode gives "AttributeError: readonly attribute"

### ISSUE THREAD

**Issue by troyrock** [jsonpickle/jsonpickle#371]
I am a new user of jsonpickle.  I'm using it to save data from simulation runs so that I can go back and do more data analysis later.   I'm encoding is a list of objects (sat_list) of a complex class that includes lists, other objects, and simple data types.  Here is the code where I am saving the data:

```
import json
import jsonpickle
sat_list_JSON = jsonpickle.encode(sat_list, unpicklable=True)
file = open("output_sat_list_1.json", "w")
json.dump(sat_list_JSON, file)
file.close()

```
The code to restore is similarly simple:

```
import json
import jsonpickle
file = open("output_sat_list_1.json", "r")
sat_list_JSON = json.load(file)
file.close()
sat_list = jsonpickle.decode(sat_list_JSON)
```

Another list of different objects works but this one gives me an error when I try to decode it:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> C:\Users\TROCKW~1\AppData\Local\Temp/ipykernel_19136/594918999.py in <module>
>     444 sat_list_JSON = json.load(file)
>     445 file.close()
> --> 446 sat_list = jsonpickle.decode(sat_list_JSON)
>     447 
>     448 # Figure out how well we did
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in decode(string, backend, context, keys, reset, safe, classes)
>      48     context = context or Unpickler(keys=keys, backend=backend, safe=safe)
>      49     data = backend.decode(string)
> ---> 50     return context.restore(data, reset=reset, classes=classes)
>      51 
>      52 
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in restore(self, obj, reset, classes)
>     161         if classes:
>     162             self.register_classes(classes)
> --> 163         value = self._restore(obj)
>     164         if reset:
>     165             self._swap_proxies()
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore(self, obj)
>     194         else:
>     195             restore = self._restore_tags(obj)
> --> 196         return restore(obj)
>     197 
>     198     def _restore_tags(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_list(self, obj)
>     523         parent = []
>     524         self._mkref(parent)
> --> 525         children = [self._restore(v) for v in obj]
>     526         parent.extend(children)
>     527         method = _obj_setvalue
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in <listcomp>(.0)
>     523         parent = []
>     524         self._mkref(parent)
> --> 525         children = [self._restore(v) for v in obj]
>     526         parent.extend(children)
>     527         method = _obj_setvalue
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore(self, obj)
>     194         else:
>     195             restore = self._restore_tags(obj)
> --> 196         return restore(obj)
>     197 
>     198     def _restore_tags(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object(self, obj)
>     357             return self._mkref(obj)
>     358 
> --> 359         return self._restore_object_instance(obj, cls)
>     360 
>     361     def _restore_function(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance(self, obj, cls)
>     419             return instance
>     420 
> --> 421         instance = self._restore_object_instance_variables(obj, instance)
>     422 
>     423         if _safe_hasattr(instance, 'default_factory') and isinstance(
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance_variables(self, obj, instance)
>     475 
>     476     def _restore_object_instance_variables(self, obj, instance):
> --> 477         instance = self._restore_from_dict(obj, instance)
>     478 
>     479         # Handle list and set subclasses
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_from_dict(self, obj, instance, ignorereserved)
>     444             k = restore_key(k)
>     445             # step into the namespace
> --> 446             value = self._restore(v)
>     447             if util.is_noncomplex(instance) or util.is_dictionary_subclass(instance):
>     448                 try:
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore(self, obj)
>     194         else:
>     195             restore = self._restore_tags(obj)
> --> 196         return restore(obj)
>     197 
>     198     def _restore_tags(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object(self, obj)
>     357             return self._mkref(obj)
>     358 
> --> 359         return self._restore_object_instance(obj, cls)
>     360 
>     361     def _restore_function(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance(self, obj, cls)
>     419             return instance
>     420 
> --> 421         instance = self._restore_object_instance_variables(obj, instance)
>     422 
>     423         if _safe_hasattr(instance, 'default_factory') and isinstance(
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance_variables(self, obj, instance)
>     475 
>     476     def _restore_object_instance_variables(self, obj, instance):
> --> 477         instance = self._restore_from_dict(obj, instance)
>     478 
>     479         # Handle list and set subclasses
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_from_dict(self, obj, instance, ignorereserved)
>     444             k = restore_key(k)
>     445             # step into the namespace
> --> 446             value = self._restore(v)
>     447             if util.is_noncomplex(instance) or util.is_dictionary_subclass(instance):
>     448                 try:
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore(self, obj)
>     194         else:
>     195             restore = self._restore_tags(obj)
> --> 196         return restore(obj)
>     197 
>     198     def _restore_tags(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object(self, obj)
>     357             return self._mkref(obj)
>     358 
> --> 359         return self._restore_object_instance(obj, cls)
>     360 
>     361     def _restore_function(self, obj):
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance(self, obj, cls)
>     419             return instance
>     420 
> --> 421         instance = self._restore_object_instance_variables(obj, instance)
>     422 
>     423         if _safe_hasattr(instance, 'default_factory') and isinstance(
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_object_instance_variables(self, obj, instance)
>     475 
>     476     def _restore_object_instance_variables(self, obj, instance):
> --> 477         instance = self._restore_from_dict(obj, instance)
>     478 
>     479         # Handle list and set subclasses
> 
> ~\Anaconda3\lib\site-packages\jsonpickle\unpickler.py in _restore_from_dict(self, obj, instance, ignorereserved)
>     458                     continue
>     459             else:
> --> 460                 setattr(instance, k, value)
>     461 
>     462             # This instance has an instance variable named `k` that is
> 
> AttributeError: readonly attribute

Here is the class definition:
```
class satellite:
    'Base class for satellites'
    TLE = None   # Another class
    sat_type = None
    SGP4_sat = None   # Another class
    beam_list = None   # List of another class
    plot_points = None
    connect_points = None
    color = None
    history = None
    sat_num = None
    num_beams = None
    bandwidth_per_beam = None
    beam_sizes = None
    beam_arrangement = None
    orbit_type = None
    
    def __init__(self, TLE, sat_type, sat_num):
        self.TLE = TLE
        self.sat_num = sat_num
        self.sat_type = sat_type;
        self.SGP4_sat = EarthSatellite(TLE[0], TLE[1])
        start_time = ts.from_datetime(self.SGP4_sat.epoch.utc_datetime())
        self.geocentric = self.SGP4_sat.at(start_time)
        self.latitude, self.longitude, self.elevation = self.geocentric.frame_latlon(itrs)
        self.location = (self.latitude.degrees, self.longitude.degrees)
        self.beam_list = []
        self.num_beams = satellite_number_of_beams[self.sat_type]
        self.beam_size = satellite_beam_size[self.sat_type]
        self.bandwidth_per_beam = satellite_bandwidth_per_beam[self.sat_type]
        self.beam_arrangement = satellite_beam_arrangement[sat_type]
        self.steer_extent = satellite_steer_extent[sat_type]
        self.connect_points = []
        self.color = satellite_unit_color[sat_type]
    
    def init_comms(self):
        beam_num = 0
        for band in comm_band_list:
            for b in range(self.num_beams[band]):
                if self.beam_arrangement == "steerable":
                    self.beam_list.append(Beam(beam_num, self, band, self.location, self.beam_size[band], self.bandwidth_per_beam[band]))
                else:
                    self.beam_list.append(Beam(beam_num, self, band, beam_locs[beam_num], self.beam_size[band], self.bandwidth_per_beam[band]))
                beam_num += 1

        
    def update_location(self, current_time):
        self.geocentric = self.SGP4_sat.at(current_time)
        self.latitude, self.longitude, self.elevation = self.geocentric.frame_latlon(itrs)
        self.location = (self.latitude.degrees, self.longitude.degrees)
        
        for band in comm_band_list:
            for beam in self.beam_list:
                if beam.is_connected:
                    if distance.distance(beam.location, self.location) > self.steer_extent:    # old steer location is unreachable
                        beam.location = self.location
                else:  # if this beam isn't connected, drag it along with the satellite
                    beam.location = self.location
    
```

Any help is appreciated.

**Comment by Theelx** [comment]
Can you try decoding with this code:
```py
import json
import jsonpickle
with open("output_sat_list_1.json", "r") as file:
    sat_list_JSON = file.read()
    sat_list = jsonpickle.decode(sat_list_JSON)
```
I think the issue is that json.load(file) returns a python objects rather than the string that jsonpickle.decode expects. In addition, file.open() and file.close() are recommended against these days, because using the context manager ``with`` allows for automatic memory management from python.

**Comment by troyrock** [comment]
That fixed it!  I'm confused because I decoded a list of a different (simpler) object and it worked:

```
file = open("output_unit_list_1.json", "r")
unit_list_JSON = json.load(file)
file.close()
unit_list = jsonpickle.decode(unit_list_JSON)
```

The sat_list is much larger, maybe that's the difference.  Regardless, thank you for your help!

**Comment by troyrock** [comment]
I spoke too soon, I'm still getting errors:
When I try to load with: 

> import json
> import jsonpickle
> with open("output_sat_list_1.json", "r") as file:
>     sat_list_JSON = file.read()
>     sat_list = jsonpickle.decode(sat_list_JSON)

It doesn't recognize the JSON object.  When I try to access the history field in the list of sats, I get the following:

> AttributeError: 'str' object has no attribute 'history'

When I try to load the filename or else loads the string from the file.read() and then do a decode, I get the same error as before.

Is is possible that jsonpickle.decode doesn't handle very large inputs (in this case ~700 MB)?  Thank you.

**Comment by Theelx** [comment]
I don't know the original structure of your data but I believe jsonpickle is working, as it seems to reconstruct sat_list as a list (otherwise, if it weren't a list, doing ``sat_list[sat_to_sample]`` would raise an error). Since ``sat_list[sat_to_sample]`` is a string, could you show the result of ``print(sat_list[sat_to_sample])``? I just want to check if it's a jsonpickle-encoded string, or one that might be decodeable on my end (so that I have a test string to fiddle/debug with).

> Is is possible that jsonpickle.decode doesn't handle very large inputs (in this case ~700 MB)?
That's absolutely possible, but my expectation is that the program would run out of memory or lag uncontrollably in that case.

**Comment by Theelx** [comment]
> sat_list_JSON = jsonpickle.encode(sat_list, unpicklable=True)

I just noticed that in the original message, you mentioned encoding with this line. If you encode without ``unpickleable=True`` then try to decode it, does it work? Setting unpickleable to True is meant to make it human-readable, which can assist in debugging simple objects' representations. The problem is, that relative simplicity makes it impossible to decode an exact copy of certain encoded non-primitive objects. I'm unsure of the exact criteria that it takes to render an encoded object undecodeable, as I haven't really played around with it that much. I suspect that this could be the source of the problem.

**Comment by troyrock** [comment]
Thanks you for your help.  I appreciate it.  I am running a simulation with `unpickleable = False` but it takes a while to run so I'll have to get back to you on the results.

I have two data structures that I'm saving to different files.  The "units" data structure is similar in many respects except that it's much smaller (~19 MB).  When I run the following code:

```
import json
import jsonpickle
print("reading in unit file.")
with open("1/output_unit_list_1.json", "r") as file:
    inputs = file.read();
    unit_list_JSON = json.loads(inputs)
    unit_list = jsonpickle.decode(unit_list_JSON)
    print(unit_list[1])   
```

I get the following output:

> reading in unit file.
> <__main__.unit object at 0x00000250DB9BDFD0>

I run similar code for the sat_list object which has a file that is ~700 MB:

```
print("reading in sat file.")
with open("1/output_sat_list_1.json", "r") as file:
    inputs = file.read();
    print("loading JSON string.")
    sat_list_JSON = json.loads(inputs)
    print("decoding JSON pickle.")
    sat_list = jsonpickle.decode(sat_list_JSON)
    print(sat_list[1])
```

This gives me the error output:

> reading in sat file.
> loading JSON string.
> decoding JSON pickle.
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> ...

If I instead run the following:
```
print("reading in sat file.")
with open("1/output_sat_list_1.json", "r") as file:
    inputs = file.read();
    print("decoding JSON pickle.")
    sat_list = jsonpickle.decode(inputs)
    print(sat_list[1])
```

I get the output:

> reading in sat file.
> decoding JSON pickle.
> {

Then if I run:
`print(sat_list[0:100])`

I get:
> [{"py/object": "__main__.satellite", "TLE": ["1 70000U 99999ZZZ 21079.40069444  .00022359  00942-5 

which shows me that it's a string, not a python list.

I'm using about 26% of my computer's memory running jupyter lab on windows.  When I run the program to read in the data, it changes a little bit but not very much (maybe up to 32% but never past 36%) so I don't think that it's running out of memory and it returns with the error pretty quickly.  If it was running out of memory, I would expect it to climb to a much larger number and also take much longer.

**Comment by troyrock** [comment]
My simulation with `unpickleable=False` completed and has an interesting result which is that instead of a python object, I now get the following:

> reading in unit file.
> {'location': [56.268475261738274, -150.36285434369336], 'unit_type': 0, 'unit_num': 1, 'revisits_satisfied': 6, 'last_visited': 17375.0, 'band': 'Ku-Ka', 'streaming': True, 'dwell_time': 0.0, 'revisit_time': 0.0, 'bandwidth': 100000000, 'is_connected': False, 'history': [[1585.0, 1], [2285.0, -1], [6185.0, 21], [6880.0, -1], [7050.0, 19], [7750.0, -1], [11205.0, 39], [11910.0, -1], [15805.0, 59], [16500.0, -1], [16675.0, 57], [17375.0, -1]]}

It works for both the unit and the sat but it's a dictionary instead of a python object.  I think that this is progress if I can figure out a way to convert it from a dictionary back to an object.  Any suggestions?

**Comment by Theelx** [comment]
That's great! If each key-value pair in the dictionary represents an attribute-value for the class, it should be pretty simple to convert from the dictionary to a class instance:
```py
class Satellite:
    def __init__(self):
        pass

mysatelitte = Satelitte()

mydict = {'location': [56.268475261738274, -150.36285434369336], 'unit_type': 0, 'unit_num': 1, 'revisits_satisfied': 6, 'last_visited': 17375.0, 'band': 'Ku-Ka', 'streaming': True, 'dwell_time': 0.0, 'revisit_time': 0.0, 'bandwidth': 100000000, 'is_connected': False, 'history': [[1585.0, 1], [2285.0, -1], [6185.0, 21], [6880.0, -1], [7050.0, 19], [7750.0, -1], [11205.0, 39], [11910.0, -1], [15805.0, 59], [16500.0, -1], [16675.0, 57], [17375.0, -1]]}

for attribute, value in mydict.items():
    setattr(mysatellite, attribute, value)

print(mysatellite.location) # [56.268475261738274, -150.36285434369336]
```

**Comment by Theelx** [comment]
Also, I apologize for this following question being completely unrelated to jsonpickle. I saw you're a computational physicist with some experience in quantum physics according to researchgate. As an undergraduate physics student at an American university myself, my end goal is to become a researcher that models and designs quantum computers using classical computational tools. I'm exploring whether to go into computational physics for a graduate degree or quantum computing, and I haven't found any career computational physicists willing to give advice about the path to take. I've asked a few of my professors, but they don't have any experience in the computational physics aspect. I was wondering if you had any idea about a good way to approach computational quantum computing?

Again, I am extremely sorry if this is improper, you don't have to answer.

**Comment by troyrock** [comment]
Thank you very much for that solution!  It's perfect.  As for being a computational physicist versus quantum computing.  I recently switched jobs from work doing quantum computers to one doing satellite constellation design and analysis.  If you specialize in quantum computing, you will be better prepared to go very deep into that area but less able to switch between different fields.  Since I love learning about lots of different things, computational physics is perfect for me.  In my work I have done laser design and optimization, quantum computing architecture design and optimization, ab initio electron structure calculations, multi-physics heat transfer and electrical simulations within laser and waveguide structures, circuit design and optimization and now finally satellite constellation design for connectivity and surveillance coverage.  I don't expect this to be the end.  My "Brand" with my work mates is that when there is something to be done and no one knows how to do it, I will take it on and I can work at a world class level within a year.  If you really want to focus on quantum computing and have a passion for it, focus on it.  If you are like me and can't decide what you want to be when you grow up, choose computational physics. :-)  Thanks again for your help.  If there is anything that I can do to return the favor, don't hesitate to let me know.
