### ISSUE TITLE
[HELP] on how to use handlers

### ISSUE THREAD

**Issue by antoinecollet5** [jsonpickle/jsonpickle#379]
Hi !

What I am trying to do is very simple. I pickled some objects a while ago and since then classes have evolved. i would like to rename some attributes on the fly to ensure retro-compatibility.

What's the best (cleanest) way to do that ?

I tried with handler something like:

```
@jsonpickle.handlers.register(MyClass, base=True)
class MyClassHandler(jsonpickle.handlers.BaseHandler):
    def restore(self, data):
        obj = self.context._restore_object_instance(data, MyClass)
        # Here I do something with my object
        return obj

    def flatten(self, obj, data):
        ....
```
But it does not seem to work :/

**Comment by Theelx** [comment]
I would try using the ``__setstate__`` method to reassign attributes when loading. This is an example where I assume you're using ``__slots__``, but it would also work if you 're using ``__dict__`` (just replace slots with dict):
```py
class MyClassV2:
    # let's assume the old class had attributes 'attr1' and 'attr2'
    # and we renamed 'attr2' to 'attr3' for the new class
    __slots__ = ('attr1', 'attr3')

    def __init__(self, attr1, attr3):
        self.attr1 = attr1
        self.attr3 = attr3

    def __setstate__(self, state):
        if 'attr2' in state:
            # now we're dealing with an instance of the old class
            # so we remove attr2 from the state dict and put its value in attr3
            state['attr3'] = state.pop('attr2')
        for slot, value in dict(state).items():
            setattr(self, slot, value)
```

**Comment by antoinecollet5** [comment]
Thank you for this answer.

How ever, it did not work. The `__setstate__` method is never called.

It seems that I need to have `__setstate__` in the class before I freeze the instance, so it creates the required field in the json file which triggers the `__setstate__` method when loading back.

Cheers !
