### ISSUE TITLE
RFC: Reduce options for pickling/unpickling

### ISSUE THREAD

**Issue by Theelx** [jsonpickle/jsonpickle#390]
The title is slightly misleading in that options won't be removed, but rather consolidated. I've become a big fan of the builtin `enums` module in Python, specifically [bitflags](https://docs.python.org/3/library/enum.html#flag). I wanted to ask for comments on the following idea:
- All True/False options would be removed from the Pickler and Unpickler objects, and replaced with a single `options` parameter.
- jsonpickle would have a new `enums.py` file, which would contain something like the following:
```py
from enum import Flag

class PicklingOptions(Flag):
    unpickleable = auto()
    make_refs = auto()
    keys = auto()
    reset = auto()
    warn = auto()
    use_decimal = auto()
    use_base85 = auto()
    include_properties = auto()

    @classmethod
    def load(cls, keys=[]):
        if isinstance(keys, list):
            flag = sum(getattr(cls, key).value for key in keys)
        elif isinstance(keys, dict):
            flag = sum(getattr(cls, key).value for key, val in keys.items() if val)
        else:
            raise NotImplementedError("keys must be a list or dict!")
        return cls(flag)

    def values(self):
        return set(key for key, member in self.__class__.__members__.items() if member in self)
```
As well as a corresponding enum for Unpickler options.
- An instance of these respective classes would be passed to a single parameter in the encode/decode functions

Rationale:
- This essentially lets us enforce that the options must be True/False, since the flag won't accept other values.
- It doesn't require setting like 10 attributes on the pickler/unpickler classes, just one.

**Comment by stefan6419846** [comment]
From my experience with Python modules, such bit masking is a rather uncommon approach. I know of parameter container classes for handling all types of values, but the enumeration stuff is something which seems to be more popular in other programming languages like C.

That said, I am not really sure if this change makes sense as it is a rather large one in my opinion. For me it usually is much easier to read/understand keyword-based arguments instead of simple numeric values.

**Comment by Theelx** [comment]
Yeah, it's absolutely an uncommon approach for Python. I think your objection makes sense, do you have any alternative suggestions that could lower the amount of keyword arguments while retaining functionality, or do you think the current system is fine?

**Comment by stefan6419846** [comment]
I have to admit that I use a very limited set of the provided features and for me the current approach is fine for now.

**Comment by Theelx** [comment]
This is likely not going to happen due to the feedback received, so I'm going to close this.
