### ISSUE TITLE
Enroll with Tidelift

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#404]
I've been enrolled with Tidelift since its first expansion to Python packages and I'm excited about the work Tidelift is doing to _Pay the Maintainers_. That is, they're trying to provide a managed path to compensate the maintainers of open source projects that add value to the world.

As I'm listed as a maintainer of jsonpickle in PyPI, I've seen this project on my list of projects for some time, and recently funding became available for this project (a modest amount).

I'd like to offer to get the active maintainer(s) enrolled with Tidelift and get this project enrolled. There are a few small requirements necessary to enroll the project, mainly to verify licensing, declare which releases are supported, and establish a security policy (where Tidelift will help).

I'm happy to help get this project enrolled if @davvid and @Theelx are interested. Presuming you wish to proceed, next steps are:

- get signed in with Tidelift as a maintainer (let me know if you need an invitation).
- allocate the jsonpickle project to the maintainers (probably an email to Tidelift indicating percentage which maintainers). At the current level of funding, they may or may not be willing to split it.

Let me know if you have any questions. If you have confidential questions that you wish not to be public, feel free to reach out to me on Gitter (jaraco), Discord (jaraco#5618), or email (visible through projects I maintain).

**Comment by Theelx** [comment]
I sent you a friend request on Discord. David and I have discussed it a bit over email and I'd be happy to fill you in.

**Comment by davvid** [comment]
I've enrolled as well. Thanks @Theelx and @jaraco 

We also fixed up the license errors in #405 so that github properly detects the BSD 3-clause ("New BSD") license.
