### ISSUE TITLE
pandas dataframe with list as values

### ISSUE THREAD

**Issue by feizerl** [jsonpickle/jsonpickle#407]
Consider this code:

```py
import jsonpickle
import jsonpickle.ext.numpy as jsonpickle_numpy
import jsonpickle.ext.pandas as jsonpickle_pandas
import pandas as pd

jsonpickle_pandas.register_handlers()
jsonpickle_numpy.register_handlers()


a = pd.DataFrame({"date": [["20220921"]]})
b = jsonpickle.decode(jsonpickle.encode(df, keys=True))
```

if you run this, you get:

```py
$ py -i foo.py 
>>> a['date'][0]
['20220921']
>>> b['date'][0]
"['20220921']"
```

i.e. a `list[str]` has been changed to a `str`

Is there any way to avoid this?

**Comment by Theelx** [comment]
Update: This is definitely a bug, and it'll be hard to fix. Pandas doesn't have a string dtype, only an object dtype, so it's hard for jsonpickle's pandas extension to differentiate between non-integer types, such as a list and a string. I'm working on fixing the encoding for that, but it'll be difficult as I need to integrate type() checking too, in addition to dtype checking.

**Comment by Theelx** [comment]
Update 2: I just realized this'll be harder to fix than I previously thought, since the lists can contain more than one dtype. For example, one could have a dataframe like so: ``pd.DataFrame({"date": [["20220921", 20220921]]})``, which has string and int dtypes inside the list. This means we'll have to store the dtypes for every single item inside the list, which is going to massively bloat the encoded blob. I'm reconsidering whether it's worth fixing this bug in the general case of a multi-dtype list.

**Comment by Theelx** [comment]
Apparently this is basically the same issue as #358.

**Comment by Paradoxdruid** [comment]
I wanted to use jsonpickle for a bioinformatics project of mine, but this behavior is a killer; I regularly have dataframes with lists of floats.

Could an implementation like this, which stores lists as lists of tuples of (value, type), be useful?  It roughly doubles the size of the representation of lists as values in pandas Series, but wouldn't touch elsewhere, I think.

```python
# a naive implementation
def list_flatten(list_input: List[Any]) -> str:
    nested_list = [f"({each}, {type(each).__name__})" for each in list_input]
    return json.dumps(nested_list)

def unflatten_list(str_input: str) -> List[Any]:
    obj = json.loads(str_input)
    final_list: List[Any] = []
    for each in obj:
        value, str_type = each.split(",")
        str_type = str_type.strip()
        if str_type == "int":
            final_list.append(int(value))
        elif str_type == "float":
            final_list.append(float(value))
        # Add datetime, etc; or recursively call for nested lists
        else:
            final_list.append(value)
    return final_list
```

Then, an example:
```python
# Example Encoding
sample = [1, 1.0, "Sue"]
list_flatten(sample)
# Output
'["1, int", "1.0, float", "Sue, str"]'

# Example Decoding
str_sample = '["1, int", "1.0, float", "Sue, str"]'
unflatten_list(str_sample)
# Output
[1, 1.0, 'Sue']
```

So, you'd add a new check in the `PandasSeriesHandler` or something:
```python
if isinstance(value, list):
    value = list_flatten(value)
```

**Comment by Theelx** [comment]
Oh, if that works I'd be happy to merge it! I'll try and test it over the next few days, thanks so much for giving some example code!

**Comment by Paradoxdruid** [comment]
Thanks, @Theelx !  Looking back at it this naïve implementation I wrote, we might need to use a special character in the f-string--  as I wrote it, if any of the string values in the list contain a comma, it will error out.  Given that `"Los Angeles, California"` would be a reasonable string to have encoded in a dataset, failing on a comma is probably a bad idea.  :wink:

**Comment by Theelx** [comment]
Hm, breaking on a special character isn't a good idea for library code. I'll try to change the behavior so it works for everything.

**Comment by Fujailashahnaj** [comment]
Can you please assign me for the issue #407?

**Comment by stefan6419846** [comment]
No need to explicitly assign you to this issue - just start working on it and open a PR (maybe as a draft at first).

**Comment by Dickensia** [comment]
Hi everyone, is there any progress on this issue?  Seems the project stuck here for a long time. I'm working on a traffic replay framework which has an urgent need for a human-readable serialization tool. When I tested with jsonpickle, it went wrong when deserialize dataframes. How can I bypass this behavior? Can you give me some advise?

**Comment by Theelx** [comment]
Hey, sorry for the long delay on getting this issue resolved. You might be able to adopt paradoxdruid's encode/decode implementation as a handler to customize the encoding/decoding for now, until I can get an actually decent solution written. I'll look back into fixing this today or tomorrow.

P.S. If the traffic replay tool needs to be used at scale (like most), then jsonpickle wouldn't be a good tool in the first place due to performance issues.

**Comment by Dickensia** [comment]
> Hey, sorry for the long delay on getting this issue resolved. You might be able to adopt paradoxdruid's encode/decode implementation as a handler to customize the encoding/decoding for now, until I can get an actually decent solution written. I'll look back into fixing this today or tomorrow.
> 
> P.S. If the traffic replay tool needs to be used at scale (like most), then jsonpickle wouldn't be a good tool in the first place due to performance issues.

Thx, I will consider about paradoxdruid's solution. And can you give a bit more detail about performance issues? Actually I'm gonna  serialize web service's output in production environment, then de-serialize them in test env, so I pay more attention about the serialization performance. The reason why I prefer jsonpickle rather than other pickle tools is because I want the serialized data human-readable and editable, like I can modify the final replay result by editing the intermediate output. If I put the serialization process in an asynchronous thread do you think it will help?

**Comment by Theelx** [comment]
> > Hey, sorry for the long delay on getting this issue resolved. You might be able to adopt paradoxdruid's encode/decode implementation as a handler to customize the encoding/decoding for now, until I can get an actually decent solution written. I'll look back into fixing this today or tomorrow.
> > P.S. If the traffic replay tool needs to be used at scale (like most), then jsonpickle wouldn't be a good tool in the first place due to performance issues.
> 
> Thx, I will consider about paradoxdruid's solution. And can you give a bit more detail about performance issues? Actually I'm gonna serialize web service's output in production environment, then de-serialize them in test env, so I pay more attention about the serialization performance. The reason why I prefer jsonpickle rather than other pickle tools is because I want the serialized data human-readable and editable, like I can modify the final replay result by editing the intermediate output. If I put the serialization process in an asynchronous thread do you think it will help?

Sorry for the late response again, I didn't get a notification for this. The performance should be much better in an environment where you can use multiple cores, like with multiprocessing. The performance issues are only relative to cPickle and such, it should still be very fast (on the order of ~100 microseconds, aka 10000 encodes/second) depending on the size of your dataframe. I'd just recommend not serializing every single packet, but only a certain percentage, to minimize costs if you're using a meteredcloud environment. Also, I got a solution for this working with dataframes, and I'm currently trying to generalize it to series and other pandas objects before I make a PR.
