### ISSUE TITLE
decode fails to raise exception when encoded string is tampered with

### ISSUE THREAD

**Issue by oberluz** [jsonpickle/jsonpickle#409]
Hi,

I created a unit test to check that if I tampered with an encoded json string it would fail to create the expected python object when decoded:

`Original encoded string = '{"py/object": "common.Test", "centre_pos": {"py/tuple": [5, 6]}, "size": {"py/tuple": [6, 6]}, "classification": "car", "tracking_id": -1, "direction": {"py/tuple": [0, 0]}, "speed": 0, "ignore_detection": false}'`

`Tampered string = '{"py/object": "common.Test", "xyz": {"py/tuple": [5, 6]},"size": {"py/tuple": [6, 6]}, "classification": "car", "tracking_id": -1,"direction": {"py/tuple": [0, 0]}, "speed": 0, "ignore_detection": false}'`

ie I changed the centre_pos member to xyz

The tampered string decodes without throwing any errors and creates a malformed 'common.Test' object.
it seems jsonpickle fails to check if a json field is part of the class it is supposed to reconstruct.

I'm encoding using:
`jsonpickle.encode(s, backend=jsonpickle.backend.JSONBackend(fallthrough=True))`
and decoding using:
`o = jsonpickle.decode(s, backend=jsonpickle.backend.JSONBackend(fallthrough=True))`

Is this expected behaviour and if so what do I need to do to have the error be detected?

**Comment by Theelx** [comment]
This is expected behavior, and the way to detect it is to run a check similar to ```py
if hasattr(obj, "attr") and obj.attr == malformed_thing:
    return
```

**Comment by oberluz** [comment]
@Theelx so to clarify:
 the user of the library is supposed to run this check **after** the object has been decoded?
what is obj in the example you gave?

**Comment by Theelx** [comment]
@oberluz That is correct, the user should run the check after the object is decoded. In case you're trying to decode data that may have been tampered with, you shouldn't be decoding untrusted data anyway, as that's a security risk, just like with cPickle, eval, or basically any other way to represent arbitrary Python objects.

**Comment by oberluz** [comment]
Agree, which is why i'd like to detect this after or during decoding.

Regarding your suggestion.
```
if hasattr(obj, "attr") and obj.attr == malformed_thing:
    return
```
If obj is the decoded object I presume "attr" is then "xyz" in my example case. What is malformed_thing then?

**Comment by Theelx** [comment]
I apologize, my malformed_thing example was bad. I meant to say if the object's attribute wasn't equal to whatever you want it to be equal to (and therefore it was corrupted), then return or raise an exception or handle it however.

I believe jsonpickle doesn't have all the information that you suggest it does when decoding the class. The only information it has is what attributes the encoded object has, it doesn't know the exact attributes of the real class when decoding. This may be wrong, so I'll look more into the code, but my initial impression is that jsonpickle couldn't detect it even if it wanted to.

If jsonpickle does have information about the class when decoding, then a check could be implemented in jsonpickle. What might be a better workaround in that case though is to use `__slots__` on the class, so then Python will error if jsonpickle tries to set an attribute that shouldn't exist.

**Comment by oberluz** [comment]
> I believe jsonpickle doesn't have all the information that you suggest it does when decoding the class. The only information it has is what attributes the encoded object has, it doesn't know the exact attributes of the real class when decoding. This may be wrong, so I'll look more into the code, but my initial impression is that jsonpickle couldn't detect it even if it wanted to.

Yes, you are correct. You can't get the instance attributes defined in __init__ (eg self.centre_point) by looking at the class

> If jsonpickle does have information about the class when decoding, then a check could be implemented in jsonpickle. What might be a better workaround in that case though is to use `__slots__` on the class, so then Python will error if jsonpickle tries to set an attribute that shouldn't exist.

I think properties is the way to go. Those are visible in a static method, eg

 properties = [i for i in cls.__dict__.keys() if isinstance(getattr(cls, i), property)]

But obviously this couldn't be done inside jsonpickle as most users won't use properties

I think I'll implement my classes using properties and then use the list above to check for a malformed object

Thanks for your help @Theelx
