### ISSUE TITLE
Stop pinning back setuptools

### ISSUE THREAD

**Issue by bmw** [jsonpickle/jsonpickle#424]
https://github.com/jsonpickle/jsonpickle/blob/f58e50cf782296c09c5fb46f90da142e094258a1/pyproject.toml#L2-L3 works in the short term, but it excludes you and your users from any setuptools fixes/improvements.

One example of this is older versions of setuptools can raise deprecation warnings on Python 3.11 due to [their use of the module sre_constraints](https://github.com/pypa/setuptools/blob/v58.5.3/setuptools/_vendor/pyparsing.py#L87) which was [deprecated in Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#modules) and is something [they fixed in setuptools 62.3.0](https://github.com/pypa/setuptools/blob/6f7dd7c12ceffa2aefe28c2fbafbad2273980b2b/CHANGES.rst#v6230).

**Comment by Theelx** [comment]
Sorry, I thought I had removed the pin, it's back from when scipy wasn't building on GHA with setuptools >=59, but it's not necessary anymore.

**Comment by gbdlin** [comment]
Can a 3.0.1 version be released with this pin removed?

**Comment by Theelx** [comment]
Yeah sure, I'll try to do it tomorrow morning

**Comment by Theelx** [comment]
3.0.1 has been released! https://pypi.org/project/jsonpickle/
