### ISSUE TITLE
include_properties fails encoding of class attributes that are a set

### ISSUE THREAD

**Issue by steinmig** [jsonpickle/jsonpickle#437]
```python
from jsonpickle import encode

class A:
    a = set(["foo", "bar"])

obj = A()
print(encode(obj,
       unpicklable=True,
       make_refs=False,
       warn=True,
       max_iter=-1,
       indent=2,
       separators=(",", ": "),
       include_properties=True,
))
```

Fails with 
```
TypeError: {'foo', 'bar'} is not JSON serializable
```

Turning the set to a tuple or setting `include_properties` to `False` allows to encode the object

**Comment by Theelx** [comment]
That's interesting. I'll try to figure out what's happening, but thanks for including a temporary workaround!

**Comment by Theelx** [comment]
Apparently json doesn't have a way to natively represent sets, so this can't be supported, and is therefore a documentation issue. `include_properties` is specifically for analyzing python/json data outside of python, and other languages can't be guaranteed to interpret any jsonpickle-only format.
