### ISSUE TITLE
Float key of defaultdict(float) is changed to string key

### ISSUE THREAD

**Issue by hubtub2** [jsonpickle/jsonpickle#440]
A defaultdict of float type does not serialize correctly. The float key is converted to a string key during encode(), but is not converted back in decode().

```
from collections import defaultdict
x = defaultdict(float)
x[0.1]=0
jsonpickle.encode(x)
```

Output:
`'{"py/object": "collections.defaultdict", "0.1": 0, "default_factory": {"py/type": "builtins.float"}}'`

One sees: the float key 0.1 became a string key "0.1"

**Comment by Theelx** [comment]
Never mind, I was wrong, this is not a bug. @hubtub2, you need to pass `keys=True` to `jsonpickle.encode` and `jsonpickle.decode`, like so:
```py
from collections import defaultdict
x = defaultdict(float)
x[0.1]=1
y = jsonpickle.encode(x, keys=True)
z = jsonpickle.decode(y, keys=True)
assert x == z
```
By default, jsonpickle doesn't encode/decode items with non-string keys, I believe this is for maximal conformance to the JSON specs (but I'm not entirely sure why).
