### ISSUE TITLE
infinite recursion crash with a subclass of dict

### ISSUE THREAD

**Issue by jrobbins-LiveData** [jsonpickle/jsonpickle#443]
The code below reproduces a `RecursionError: maximum recursion depth exceeded in __instancecheck__` crash.
```
import jsonpickle

class Container(dict):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__dict__ = self


def main():
    c = Container(a=17)
    jsonpickle.encode(c)


if __name__ == '__main__':
    main()
```

Since `pickler.py` already seems to have code to handle subclasses of `dict`, I'm assuming that the `self.__dict__ = self` in the code above is the culprit causing the issue.  

Adding `and obj != obj.__dict__` as shown below to `pickler.py` seems to fix the problem.  Is this something you'd consider fixing, or accepting a PR to fix?

"""
File: pickler.py
773:         # Sub-classes of dict
774:         if hasattr(obj, '__dict__') and self.unpicklable `and obj != obj.__dict__`:
775:             dict_data = {}
776:             self._flatten_dict_obj(obj.__dict__, dict_data)
777:             data['__dict__'] = dict_data
"""

**Comment by Theelx** [comment]
Yes, I'd be happy to merge a PR for this (or fix it myself!) I'll leave it up to you as to whether you want to submit the PR and have it merged, to show in your GitHub activity, or whether you want me to submit it (since this is a super quick PR).

**Comment by jrobbins-LiveData** [comment]
I'm somewhat old and somewhat lazy!  If you can do it, great, cuz I'm not
super fluent with the whole PR process and fear making a mess of things!
 Do you think my suggested fix is correct?

Jeff Robbins, CEO
LiveData, Inc. https://www.livedata.com/
(617) 571-5739 mobile
LinkedIn  <https://www.linkedin.com/in/jeffsrobbins>
Twitter <https://twitter.com/jeffrobbinsceo>
2 minute video <https://youtu.be/l9CpI7XR8YU/?utm_source=s>

**Comment by Theelx** [comment]
Yep, your solution is correct!
