### ISSUE TITLE
dictionary arguments are turned into strings

### ISSUE THREAD

**Issue by julian-goettingen** [jsonpickle/jsonpickle#450]
```
>>> jsonpickle.loads(jsonpickle.dumps({1: 'a'}))
{'1': 'a'}
```
This does not seem right?
If this is an intentional or known limitation I am sorry I missed it but I do believe even in that case it should raise an error.

This is python3.7 running jsonpickle-3.0.1

**Comment by Theelx** [comment]
Hello, and thanks for your report! While I understand this is confusing behavior, it would be a backwards-incompatible change to raise an error. Also, the output you want to achieve is already possible with `keys=True`, as per the note in https://jsonpickle.readthedocs.io/en/latest/api.html#jsonpickle-high-level-api.
```py
>>> jsonpickle.loads(jsonpickle.dumps({1: 'a'}, keys=True), keys=True)
{1: 'a'}
```

**Comment by julian-goettingen** [comment]
Thank you - it is indeed explained in the documentation.
