### ISSUE TITLE
.asc missing on pypi for 3.0.2

### ISSUE THREAD

**Issue by limburgher** [jsonpickle/jsonpickle#461]
Was present for 3.0.1

**Comment by Theelx** [comment]
PyPi doesn't accept PGP/GPG signatures anymore.
![Screenshot from 2023-08-14 18-56-36](https://github.com/jsonpickle/jsonpickle/assets/43764914/d7347a2e-cff7-4fdb-918e-b251cb92fd1b)

**Comment by limburgher** [comment]
Gotcha, thank you!
