### ISSUE TITLE
Complete compliance steps in Tidelift

### ISSUE THREAD

**Issue by jaraco** [jsonpickle/jsonpickle#464]
Tidelift is reporting that @theelx has not yet completed 2FA in PyPI. I'm pretty sure that's required universally now, so probably all that's needed is to log in and declare that 2FA has been completed. Theelx, can you do that when you get a chance?

**Comment by Theelx** [comment]
I have completed 2fa in PyPi. I've been confused as to why it's been saying that.

**Comment by Theelx** [comment]
Ah, the issue was that I had a backup account without 2FA enabled. I just removed that account from the organization.

**Comment by jaraco** [comment]
It's actually a task that needs to be completed in Tidelift, one of the few tasks they ask for lifters. Go to the [tasks page for jsonpickle](https://tidelift.com/lifter/package/pypi/jsonpickle/tasks) and make sure there aren't any tasks to complete. Although you may have in fact already enrolled with 2FA (I see that), Tidelift needs you to separately assert that you have. The experience could be designed better, but they're doing their best. If you can double-check that you don't have any pending tasks or complete them, that would be best. Thanks!

**Comment by Theelx** [comment]
Oh, got it! I just completed the task, and there don't seem to be any left. Thanks!
