### ISSUE TITLE
Project's URL is not up-to-date

### ISSUE THREAD

**Issue by Lonami** [jsonpickle/jsonpickle#466]
The URL GitHub displays below the **About** is https://jsonpickle.github.io/. However, that page contains:

> [jsonpickle 1.4.3.dev0+g5b8d3ea.d20201130 documentation](https://jsonpickle.github.io/#) » [jsonpickle Documentation](https://jsonpickle.github.io/)

But I believe the latest documentation is https://jsonpickle.readthedocs.io/en/latest/ as written in the README.

(Although I can't quite tell if either is up-to-date, since the PyPi release claims 3.0.2 latest.)

**Comment by Theelx** [comment]
Thank you for reporting, I'll fix that!

**Comment by Theelx** [comment]
Update: I don't believe I have permissions to edit the About section. @davvid can you give me more permissions in the jsonpickle team or update the link in the About section yourself? Thanks in advance.

**Comment by davvid** [comment]
Thanks for the heads-up. I edited the description and added you to the `Owners` team.

You should have already been in there long ago but I hadn't noticed back when I was originally added to that team (which wasn't too long ago, actually). cheers!
