### ISSUE TITLE
Possible problem with encoding in a Aysnchronous progam when calling a task

### ISSUE THREAD

**Issue by Ducati748ss** [jsonpickle/jsonpickle#495]
Hi 
I have a python program that reads data from Modbus devices in a local network. It uses python asynchronous tasks to read various meters.

I was writing and reading an object out to a binary file within various tasks, which was working fine, however I wanted to change to a JSON file.

In the main program I can jasonpickle.encode my object with no problem. However, when I pickle the same object in a task created with asyncio.create_task, rather than jasonpickle.encode just returning only the JSON representation of the single object I’m passing it (incuding the one I want), it returns every object that the task can access!

It will take me a little while to create an MRE, so first I would like to ask if you have come across this behavior before and might be able to guide me toward a fix. 

Thanks 
Mark

I have incuded an example of the JSON file from the main program with the single object and one from teh task with all the objects
[MetSimStatusFile_MainProg.json](https://github.com/jsonpickle/jsonpickle/files/15187075/MetSimStatusFile_MainProg.json)

[MetSimStatusFile_Task.json](https://github.com/jsonpickle/jsonpickle/files/15187113/MetSimStatusFile_Task.json)

**Comment by Theelx** [comment]
Hey, I don't think I've noticed that before. I use jsonpickle inside a project that uses asyncio.ensure_future (iirc it's been removed in recent versions of Python) and jsonpickle works fine. It's interesting that this behavior is happening though, are you also using multiprocessing perchance? Also, what version of CPython and jsonpickle are you using?

**Comment by Ducati748ss** [comment]
Hi

Thanks very much for your comments and for jsonpickle.
I’m using jsonpickle-3.0.4 and Python 3.12.3, no multiprocessing.
I’ve just overcome the behaviour. I believe I was corrupting the object just prior to the call the asynchronous task. Now it is working perfectly!!
Sorry for wasting your time.
Best regards
Mark

**Comment by Theelx** [comment]
I'm glad you fixed it!

**Comment by Ducati748ss** [comment]
Hi 
Just wanted to add that, to successfully decode within the “asyinco” task, I had to add set  the 'classes' parameter within the jsonpickle.decode call, to stop conversions to a dictionary (I believe).
e.g.
`myObjectFromFile = jsonpickle.decode(decodeString, classes = myObject)`
Best Regards 
Mark
