### ISSUE TITLE
Fails trying to unpickle a Pandas Timedelta object

### ISSUE THREAD

**Issue by tjnd89** [jsonpickle/jsonpickle#497]
When trying to unpickle a Pandas Timedelta it will crash and complain 

`TypeError: 'dict' object is not callable`

This occurs with Pandas version 2.2.1, but does not occur with Pandas 2.1.4.

To reproduce this:

```
import pandas as pd
import jsonpickle
import jsonpickle.ext.pandas as jsonpickle_pandas

jsonpickle_pandas.register_handlers()
x = pd.to_timedelta(10, 's')
y = jsonpickle.decode(jsonpickle.encode(x))

print(y)
```

**Comment by tjnd89** [comment]
The jsonpickled output is:

```
                    "py/reduce": [
                        {
                            "py/object": "_cython_3_0_8.cython_function_or_method"
                        },
                        {
                            "py/tuple": [
                                86160000000000,
                                10
                            ]
                        }
                    ]
```

**Comment by tjnd89** [comment]
forgot to add I was using jsonpickle version 3.0.2.

**Comment by davvid** [comment]
Our changelog has a note about pandas v3 in the jsonpickle v3.0.3 release.

https://jsonpickle.readthedocs.io/en/latest/history.html#v3-0-3

> Compatibilty with Pandas and Cython 3.0 was added. ([#460](https://github.com/jsonpickle/jsonpickle/issues/460)) ([+477](https://github.com/jsonpickle/jsonpickle/pull/477))

Please try using a newer version. FWIW, I was able to run the snippet above and it encodes and decodes correctly.

Let us know if it's not working for you. If it's not working then I'll need you to share the output from this:

```
import pandas
print(pandas.__version__)
```


For reference, the output I see from the encoded json is:

```json
{"py/reduce": [{"py/function": "pandas._libs.tslibs.timedeltas._timedelta_unpickle"}, {"py/tuple": [10000000000, 10]}]}
```

**Comment by tjnd89** [comment]
@davvid I can confirm that it works properly using jsonpickle=3.0.4. Thanks!

**Comment by PhilippVerpoort** [comment]
Updating to latest version of `jsonpickle` also solved the issue for me. Thanks!
