### ISSUE TITLE
Handling complex cyclic object graphs with OrderedDicts

### ISSUE THREAD

**Issue by marcintustin** [jsonpickle/jsonpickle#92]
When I saw [this](http://www.petrounias.org/articles/2014/09/16/pickling-python-collections-with-non-built-in-type-keys-and-cycles/) posted on http://reddit.com/r/python, I wanted to pipe up that Jsonpickle handles cyclic structures beautifully. So, I extracted the test code, and replaced the pickle calls with jsonpickle calls, and it chokes on restoring OrderedDicts.

I've tried to figure out exactly what's wrong, but I can't. It looks like it's something to do with the cyclic list structures generated on restore. 

Here is the test code extracted from the blog post: https://gist.github.com/marcintustin/7b1c034756a77460f885

**Comment by davvid** [comment]
Recent changes actually got this test case working.

Related #193 and #286 -- the trick is to use `keys=True` when encoding and decoding.

The wizardexample.py test cases passes when adjusted to use `keys=True` when calling into jsonpickle.  There are two non-sensical assertions:

```
        # ~line 123
        self.assertEqual(morgana_spells_decoded, wizard_morgana.spells)

        # ~line 128
        self.assertEqual(wizard_morgana.__dict__, morgana_decoded.__dict__)
```

Once those are removed all of the assertions related to object identity and objects-in-dict-keys are correctly handled.
